### ISSUE TITLE
大佬 目前还支持token的方式吗？  我输入了token 报错

### ISSUE THREAD

**Issue by hewenzhuo1** [gngpp/ninja#139]
大佬 目前还支持token的方式吗？  我输入了token 报错

**Comment by gngpp** [comment]
> 大佬 目前还支持token的方式吗？ 我输入了token 报错

我知道问题了，你明天再看吧

**Comment by hewenzhuo1** [comment]
好的   感谢大佬

**Comment by gngpp** [comment]
https://github.com/gngpp/ninja/releases/tag/v0.5.2
