### ISSUE TITLE
怎么设置har文件地址呢？

### ISSUE THREAD

**Issue by liuyan345** [gngpp/ninja#142]
我打开http://127.0.0.1:7999/har/upload，
上传har文件，提示
Failed to upload file
You have to set the path of the uploaded file
意思是我在我本地运行docker时，启动要设置上传路径吗？
我看readme里面--arkose-har-file参数，但是我设置参数启动报错，这个参数是要跟我本地har文件绝对地址吗？

**Comment by gngpp** [comment]
是的，绝对地址

**Comment by gngpp** [comment]
你先把文件映射进容器，地址填容器内的文件路径就行了

**Comment by liuyan345** [comment]
OK，没有问题，我上传har文件提示成功了
另外，在登录页面的MFA Code是指的什么代码，我之后用的是access token登录的，登录之后，控制台的所有请求都是500，是要配置其他的参数吗？
我的启动命令是：docker run --rm -it -v /Users/nihao/Desktop:/Desktop  -p 7999:7999 --name=ninja   -e WORKERS=1   -e LOG=info   gngpp/ninja:latest   serve run --arkose-har-file /Desktop/chat.openai.com.har --proxies socks5://127.0.0.1:1080

**Comment by gngpp** [comment]
日志呢？开debug
