### ISSUE TITLE
可以直接在docker里使用token吗？

### ISSUE THREAD

**Issue by Joackk** [gngpp/ninja#145]
因为是个人用，把api给其他软件来用，所以用这个超长的token当key的时候，会报401，不知道是不是太长了，但是python脚本调用是正常的，想问下大佬，如何把这个token加入到docker环境里？调用时候就不要key了，直接给地址就好

**Comment by gngpp** [comment]
啥软件啊，我试过好多客户端都没啥问题啊，看看报错信息就知道了，估计是缺少Bearer前缀

**Comment by Joackk** [comment]
> 啥软件啊，我试过好多客户端都没啥问题啊，看看报错信息就知道了，估计是缺少Bearer前缀

虚拟桌宠  [VPet](https://github.com/LorisYounger/VPet)   这个，其他软件还没试，但是python中是正常的，大佬你那边可以吗？

**Comment by gngpp** [comment]
看不懂这玩意，怎么用呢

**Comment by Joackk** [comment]
![image](https://github.com/gngpp/ninja/assets/45162558/e91e8b28-94f5-427d-8e16-2d12dfa50e3f)
就是个这玩应，电子宠物一类的，设置面板这里有个gpt设置
![image](https://github.com/gngpp/ninja/assets/45162558/3337b750-4ef5-47d2-b130-0387b4263b3b)
这里可以设置接口和key
![image](https://github.com/gngpp/ninja/assets/45162558/1efa19bc-5f4d-496e-a45f-886e1e91cece)

**Comment by gngpp** [comment]
你这后缀好像有问题，chatgpt转API是：/to/...

**Comment by Joackk** [comment]
> 你这后缀好像有问题，chatgpt转API是：/to/v1/chat/completions

图里面我用的是naga的api，不是转的，我是了另一个[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)项目里试了下，在docker环境中设置了token，在外部调用时候就不需要再输入apikey，可以正常使用，大佬这个项目里可以把token设置在docker里吗？因为我是基本都在其他软体里调用，每次都输入token比较麻烦，所以直接卸载docker里调用时候只需要接口即可

**Comment by gngpp** [comment]
你想通过什么设置，环境变量？

**Comment by Joackk** [comment]
> 你想通过什么设置，环境变量？

对，可以直接在环境变量里写入账号密码来让他自动获取吗？调用的时候就不用输入key直接api来用

**Comment by Joackk** [comment]
> 你想通过什么设置，环境变量？

因为我是自己用，所以想直接用账号密码来获取token，加上使用时候主要是给其他软件用api，所以可以直接在环境变量里设置账号密码来获取token吗？调用时候就不再需要token作为key了，直接接口访问就行了
