### ISSUE TITLE
ARKOSE_HAR_UPLOAD_KEY 配置之后，上传har没有要求我输入key

### ISSUE THREAD

**Issue by mygit-2023** [gngpp/ninja#151]
感谢作者的项目，对话啥的都贼溜。

ARKOSE_HAR_UPLOAD_KEY 配置之后，上传har没有要求我输入key。
用的最新的 docker-compose,是不是还有哪里需要配置一下的。

另外跟您反馈一下，https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147 这个接口现在找不到了。

**Comment by gngpp** [comment]
是`--arkose-har-upload-key` 不是`ARKOSE_HAR_UPLOAD_KEY`
<img width="1440" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/d2ba3f20-488c-4373-98e5-7f13bcf04388">
