### ISSUE TITLE
似乎无法登录了？

### ISSUE THREAD

**Issue by a765616527** [gngpp/ninja#159]
如题，登录时候会显示
error sending request for url (https://auth0.openai.comhttps//chat.openai.com/): error trying to connect: dns error: failed to lookup address information: Name does not resolve

**Comment by spammenotinoz** [comment]
DNS issue with open AI, change to 1.1.1.1 fixed the issue for me.

**Comment by a765616527** [comment]
好的 感谢回复

**Comment by a765616527** [comment]
已修改DNS 未解决问题

**Comment by gngpp** [comment]
等更新吧，openai登录加arkose验证了
https://github.com/gngpp/ninja/actions/runs/6322937528

**Comment by gngpp** [comment]
#160
