### ISSUE TITLE
Web browsing is not available via proxy

### ISSUE THREAD

**Issue by mkurganovich** [gngpp/ninja#161]
I get this alert using my proxy server and have no "Web Browsing" option.
![image](https://github.com/gngpp/ninja/assets/90131968/2315c29b-1712-40d1-88a7-0cae817f1b97)
![image](https://github.com/gngpp/ninja/assets/90131968/d97d0d36-c76a-4dc1-9fcc-ec64bc938606)

chat.openai.com:
![image](https://github.com/gngpp/ninja/assets/90131968/dba83131-255c-400e-9ca3-7903fa4f096c)

**Comment by gngpp** [comment]
"Web Browsing" is not fully open now, and we plan to update the UI after it is open.

**Comment by gngpp** [comment]
#175
