### ISSUE TITLE
希望获取unofficial_preauth_cookie时支持传入自定义的网址

### ISSUE THREAD

**Issue by zhuxindong** [gngpp/ninja#166]
希望获取unofficial_preauth_cookie支持传入自定义的网址
https://github.com/gngpp/ninja/blob/a2c68bab8c0711710b9064eb5f0bf079e8bd4493/openai/src/auth/mod.rs#L887
![image](https://github.com/gngpp/ninja/assets/24989246/ce19c9df-af4c-44c2-8b9e-21e5b2b61eea)
是否可以做成可配置化的环境变量

**Comment by gngpp** [comment]
暂时没这个需求，你自己fork自己改吧
