### ISSUE TITLE
登录时有概率遇到 Incorrect API key provided: undefined.

### ISSUE THREAD

**Issue by su-fen** [gngpp/ninja#173]
{"detail":{"message":"Incorrect API key provided: undefined. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}

有时候登录会返回这种报错，这是哪里出问题了呢？

**Comment by gngpp** [comment]
很明显这是openai返回的错误，platform登录

**Comment by su-fen** [comment]
一直走的是apple的登录，按理来说不应该出现这种错误，很怪

**Comment by gngpp** [comment]
什么版本，登录传的参数我看看

**Comment by su-fen** [comment]
curl --location 'https://auth.xxx.com/auth/token' \
--header 'option: false' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=xxx' \
--data-urlencode 'password=xxxx' \
--data-urlencode 'option=apple'

版本是最新版

**Comment by gngpp** [comment]
确实有点奇怪，看不出什么问题，最好是开debug模式去看日志，就知道那个步骤出问题了

**Comment by su-fen** [comment]
{"detail":{"message":"The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 15f7597bdec0d025db2faa116ce4947a in your email.)","type":"server_error","param":null,"code":null}}

这是今天主要的报错，出现频率挺高。但账号密码都是正确的，官网登录都没问题。去帮助中心看是OpenAI内部错误，但感觉不太像

**Comment by su-fen** [comment]
发现了问题，重复提交会这样。同一账号同一时间在不同浏览器同时登陆其中一边就会出现这种报错

**Comment by su-fen** [comment]
> {"detail":{"message":"The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 15f7597bdec0d025db2faa116ce4947a in your email.)","type":"server_error","param":null,"code":null}}
> 
> 这是今天主要的报错，出现频率挺高。但账号密码都是正确的，官网登录都没问题。去帮助中心看是OpenAI内部错误，但感觉不太像

发现了问题，重复提交会这样。同一账号同一时间在不同浏览器同时登陆其中一边就会出现这种报错

**Comment by gngpp** [comment]
我怀疑是cookie问题，后端做了cookie存储，准备去掉试试

**Comment by gngpp** [comment]
#191
