### ISSUE TITLE
请求为 dashboard 的 apikey 操作也增加 arkose 验证

### ISSUE THREAD

**Issue by ClarenceDan** [gngpp/ninja#177]
目前在platform 的 dashboard 操作 apikey 也需要传入 arkose 参数，尝试改了一下代码没搞定，希望大佬能加上。感恩！
![apikey](https://github.com/gngpp/ninja/assets/48417261/6065d3fb-6a34-4e3b-a3cb-a5bdba60c9bc)

**Comment by gngpp** [comment]
你确定你传的token有效？现在platform很容易出码

**Comment by ClarenceDan** [comment]
> 你确定你传的token有效？现在platform很容易出码

抱歉可能没描述清楚，我的意思是这部分接口也需要传入arkose_token，但是我不太明白应该怎么做：
`
###
POST http://{{host}}/dashboard/user/api_keys
Authorization: {{bearer_session_id}}
Content-Type: application/json

{
    "action":"create",
    "name":"ninja"
}

### 
POST http://{{host}}/dashboard/user/api_keys
Authorization: {{bearer_session_id}}
Content-Type: application/json

{
    "action":"delete",
    "redacted_key":"sk-M4dpz***************************************L1o3",
    "created_at":1687341651
}
`

**Comment by gngpp** [comment]
你照着官网的参数填就对了，只是个转发，文档过时了
