### ISSUE TITLE
貌似puid 失效了，现在直接限制一个小时70条左右

### ISSUE THREAD

**Issue by TangGV** [gngpp/ninja#178]
--puid-user 'account:pass'

--puid 'cookie'
设置plus账号密码也不行，直接f12获取puls的cookie 设置也不行

**Comment by gngpp** [comment]
说明puid方案可以删除了

**Comment by gngpp** [comment]
上官网发看看限制了么，限制我就删除这个方案了

**Comment by TangGV** [comment]
> 上官网发看看限制了么，限制我就删除这个方案了

测试过限制了 你可以试试看

**Comment by gngpp** [comment]
官网都限制了，说明是彻底IP限制了，绕不开，只能上代理池了

**Comment by gngpp** [comment]
对了，换不同账号呢？

**Comment by d1h1r1** [comment]
> 官网都限制了，说明是彻底IP限制了，绕不开，只能上代理池了

我也遇上速率限制了，docker run --rm -it -p 7999:7999 --name=ninja   -e WORKERS=500   -e LOG=info -e PROXIES=https://181.232.190.242:999   gngpp/ninja:latest run，像这样只能部署一个代理IP吗，可以实时切换代理ip吗

**Comment by gngpp** [comment]
用,隔开多个代理轮训，有条件可以上一段ipv6/48

**Comment by d1h1r1** [comment]
有时候代理会失效更换比较麻烦，可以用api接口获取代理ip实时切换吗
