### ISSUE TITLE
大佬 /auth/token 接口调用不好用

### ISSUE THREAD

**Issue by dingtianlu** [gngpp/ninja#183]
大佬 /auth/token 接口直接使用不了，想编写脚本自动获取access_token ，能不能帮忙封装下 感谢大佬 @gngpp

**Comment by gngpp** [comment]
还用怎么写用？，不是填密码账号就完事了

**Comment by dingtianlu** [comment]
大佬 好像需要个arkose_token这个参数，这个参数搞不定

**Comment by gngpp** [comment]
文档不是说了？自己上传HAR特征文件

**Comment by dingtianlu** [comment]
好的好的  我仔细看下 打扰了
