### ISSUE TITLE
Failing to compile on Arch Linux

### ISSUE THREAD

**Issue by Jirubizu** [gngpp/ninja#187]
Compiling boring-sys v2.0.0 (https://github.com/gngpp/boring#c54e490f)
error: failed to run custom build command for `boring-sys v2.0.0 (https://github.com/gngpp/boring#c54e490f)`

Caused by:
  process didn't exit successfully: `/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-cbaecee17b0560c2/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=BORING_BSSL_PATH
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/jirubizu/.cargo/git/checkouts/boring-e91d5d2310e5f29a/c54e490/boring-sys/deps/boringssl" "-DCMAKE_INSTALL_PREFIX=/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=MinSizeRel"
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build
  running: cd "/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "cmake" "--build" "." "--target" "ssl" "--config" "MinSizeRel"
  [100%] Built target ssl
  cargo:root=/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out
  running: cd "/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/jirubizu/.cargo/git/checkouts/boring-e91d5d2310e5f29a/c54e490/boring-sys/deps/boringssl" "-DCMAKE_INSTALL_PREFIX=/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=MinSizeRel"
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: /home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build
  running: cd "/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "cmake" "--build" "." "--target" "crypto" "--config" "MinSizeRel"
  [100%] Built target crypto
  cargo:root=/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out
  cargo:rustc-link-search=native=/home/jirubizu/Development/Ai/ninja/target/release/build/boring-sys-40706b39376a8007/out/build/
  cargo:rustc-link-lib=static=crypto
  cargo:rustc-link-lib=static=ssl
  cargo:rerun-if-env-changed=BORING_BSSL_INCLUDE_PATH

  --- stderr
  thread 'main' panicked at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.68/src/fallback.rs:777:9:
  "__atomic_wide_counter_struct_(unnamed_at_/usr/include/bits/atomic_wide_counter_h_28_3)" is not a valid Ident
  stack backtrace:
     0:     0x559d17847e4c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x559d17847e4c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x559d17847e4c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x559d17847e4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x559d17873d5c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
     5:     0x559d17873d5c - core::fmt::write::hb8eaf5a8e45a738e
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
     6:     0x559d1784489e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
     7:     0x559d17847c34 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x559d17847c34 - std::sys_common::backtrace::print::h1360e9450e4f922a
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x559d17849503 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
    10:     0x559d1784921c - std::panicking::default_hook::h6d75f5747cab6e8d
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
    11:     0x559d17849a89 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
    12:     0x559d17849987 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
    13:     0x559d17848376 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
    14:     0x559d178496d2 - rust_begin_unwind
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    15:     0x559d17379593 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    16:     0x559d17791009 - proc_macro2::fallback::validate_ident::ha8c92a4bdf0d3815
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.68/src/fallback.rs:777:9
    17:     0x559d17790d5c - proc_macro2::fallback::Ident::_new::hd1d6d59a91471e5c
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.68/src/fallback.rs:719:9
    18:     0x559d17790dcc - proc_macro2::fallback::Ident::new::h7ce4f102aee244e9
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.68/src/fallback.rs:729:9
    19:     0x559d17793407 - proc_macro2::imp::Ident::new::h2a70ab03008b3403
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.68/src/wrapper.rs:645:50
    20:     0x559d1779f225 - proc_macro2::Ident::new::h36f4dddb367ca8d5
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.68/src/lib.rs:952:21
    21:     0x559d173f9a42 - bindgen::ir::context::BindgenContext::rust_ident_raw::hc8885b09893d5e43
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/ir/context.rs:861:9
    22:     0x559d173f96da - bindgen::ir::context::BindgenContext::rust_ident::hb9c8828fb0d75783
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/ir/context.rs:853:9
    23:     0x559d17466249 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hcfb28b23547b8143
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:1786:31
    24:     0x559d173a66c7 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::h364e92a93b47c9d4
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:814:39
    25:     0x559d17415a4d - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hd11fbe961e264f79
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:500:17
    26:     0x559d1746d0ef - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hcfb28b23547b8143
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:2115:13
    27:     0x559d173a66c7 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::h364e92a93b47c9d4
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:814:39
    28:     0x559d17415a4d - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hd11fbe961e264f79
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:500:17
    29:     0x559d174b696a - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::hcf41458159a61a4f
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:523:21
    30:     0x559d173c4c57 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::ha183b43afb230cf5
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:553:13
    31:     0x559d17415a29 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hd11fbe961e264f79
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:491:17
    32:     0x559d174c3a3f - bindgen::codegen::codegen::{{closure}}::hc732306d0b69467b
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:4364:9
    33:     0x559d173fc052 - bindgen::ir::context::BindgenContext::gen::h3ec397e22302fcfd
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/ir/context.rs:1173:19
    34:     0x559d174c319d - bindgen::codegen::codegen::he02de11090b125ff
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/codegen/mod.rs:4328:5
    35:     0x559d173d3bfd - bindgen::Bindings::generate::hfa0d60c3336d079f
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/lib.rs:2438:32
    36:     0x559d173d0d56 - bindgen::Builder::generate::hb5152e4e9122b8e0
                                 at /home/jirubizu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/lib.rs:1502:9
    37:     0x559d17383db4 - build_script_build::main::h78d8e03ff42de64a
                                 at /home/jirubizu/.cargo/git/checkouts/boring-e91d5d2310e5f29a/c54e490/boring-sys/build.rs:457:20
    38:     0x559d1737ae2b - core::ops::function::FnOnce::call_once::h67ba60198b020261
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
    39:     0x559d17379ede - std::sys_common::backtrace::__rust_begin_short_backtrace::h0c899f121dac1eda
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:154:18
    40:     0x559d1737a711 - std::rt::lang_start::{{closure}}::had618109dcc66c21
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:166:18
    41:     0x559d1784013b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
    42:     0x559d1784013b - std::panicking::try::do_call::he5f117a9e13dadde
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    43:     0x559d1784013b - std::panicking::try::h2f3af9afce3a0443
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    44:     0x559d1784013b - std::panic::catch_unwind::h6d6c387f38ef05ea
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    45:     0x559d1784013b - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
    46:     0x559d1784013b - std::panicking::try::do_call::ha9fd18ea06654a4b
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    47:     0x559d1784013b - std::panicking::try::hda5c2a4432362341
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    48:     0x559d1784013b - std::panic::catch_unwind::h440f731b142bc235
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    49:     0x559d1784013b - std::rt::lang_start_internal::hc0b4e50f058f62ce
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
    50:     0x559d1737a6ea - std::rt::lang_start::haf867660dfd3dfe8
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:165:17
    51:     0x559d17384a7e - main
    52:     0x7f47b1cd4cd0 - <unknown>
    53:     0x7f47b1cd4d8a - __libc_start_main
    54:     0x559d17379c55 - _start
    55:                0x0 - <unknown>

**Comment by gngpp** [comment]
documents：https://github.com/google/boringssl/blob/master/BUILDING.md

**Comment by Jirubizu** [comment]
> documents：https://github.com/google/boringssl/blob/master/BUILDING.md

Thank you, maybe add to a dependency list under compiling?

**Comment by gngpp** [comment]
> > documents：https://github.com/google/boringssl/blob/master/BUILDING.md
> 
> Thank you, maybe add to a dependency list under compiling?

You need to install gcc g++ cmake libclang-dev and other tool libraries to compile boringssl

**Comment by gngpp** [comment]
### docker environment build example:

```shell
# into container
docker run --rm -it ubuntu /bin/bash

apt update -y && apt install -y git curl libclang-dev build-essential pkg-config cmake ninja-build curl autoconf automake libtool

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"

git clone https://github.com/gngpp/ninja && cd ninja
cargo build --release
```
