### ISSUE TITLE
能否更新支持Plus的DALL-E 3呢

### ISSUE THREAD

**Issue by yitd** [gngpp/ninja#197]
目前好像都没有支持的

**Comment by gngpp** [comment]
什么叫好像？不是老早就更新了
![image](https://github.com/gngpp/ninja/assets/51810656/8ceb7c04-184a-4c10-90a6-2022af1188d7)

**Comment by yitd** [comment]
api 大佬

**Comment by gngpp** [comment]
API不打算维护了，你去用别人的吧
