### ISSUE TITLE
web不可以，但是https://host:port/v1/的API接入方式正常

### ISSUE THREAD

**Issue by tianlichunhong** [gngpp/ninja#199]
使用了docker-compose的方式部署。配置如下
version: '3'
services:
  ninja:
    image: ghcr.io/gngpp/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      #- TZ=Asia/Shanghai
      - PROXIES=socks5://xxxxx:1080
      - TLS_CERT=/etc/fullchain.pem
      - TLS_KEY=/etc/privkey.pem
    volumes:
      - ${PWD}/ssl:/etc
      # - ${PWD}/serve.toml:/serve.toml
    command: serve run
    ports:
      - "5799:7999"
服务是起来了。
但是打开网页版不行，能登录，但是问问题会出现如下错误。
![image](https://github.com/gngpp/ninja/assets/13270039/6d358e6b-84bd-4b98-937b-ff83e6dd17c5)

使用python的openai库通过API的接口，使用正常。代码如下：
import openai
openai.api_key = "xxxxxx"
openai.api_base = "https://xxxxxx:5799/v1"

while True:
    text = input("请输入问题：")
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {'role': 'user', 'content': text},
        ],
        stream=True,
    )
    for chunk in response:
        print(chunk.choices[0].delta.get("content", ""), end="", flush=True)
    print("\n")

请大佬看看是怎么回事？

**Comment by gngpp** [comment]
你网络有问题，我演示站都能用
