### ISSUE TITLE
docker-compose部署，ninja exited with code 139

### ISSUE THREAD

**Issue by befantasy** [gngpp/ninja#207]
使用docker-compose部署，ninja service无法启动，查看docker log提示：ninja exited with code 139

**Comment by gngpp** [comment]
别用compose了，直接docker run

**Comment by befantasy** [comment]
一样的。。。连个log都没有。

**Comment by gngpp** [comment]
那就用别人的，图都没有，你叫我怎么诊断

**Comment by befantasy** [comment]
我也想有图，我也得不到任何信息。
docker run无任何提示。
compose在log里只能看到
ninja exited with code 139。

**Comment by befantasy** [comment]
ARM镜像有问题，https://www.airplane.dev/blog/sigsegv-segmentation-fault-linux-containers-exit-code-139

一开始就提供了所有能提供的信息：ninja exited with code 139

**Comment by gngpp** [comment]
我看是你的内存有问题。
![image](https://github.com/gngpp/ninja/assets/51810656/4aa8bc78-f1a7-4c6e-8904-185417478a9e)
