### ISSUE TITLE
用 to/v1 会出现问题

### ISSUE THREAD

**Issue by heurainbow** [gngpp/ninja#216]
访问一段时间后出现。
ninja web端出现：Our systems have detected unusual activity from your system. Please try again later.
api http://XXX.xxx.xxx.xxx:7999/to/v1  会返回输入的指令
此时，官方web端是正常的。

美国的服务器挂多个账户，每个账户采用了美国住宅IP代理。

是什么原因？有没有解决思路？

**Comment by gngpp** [comment]
因为你的账号gpt3.5灰度了，不要急，会更新修复的

**Comment by gngpp** [comment]
https://github.com/gngpp/ninja/releases/tag/v0.7.2

**Comment by heurainbow** [comment]
@gngpp 更新到0.7.2后原问题已解决。但是未灰度的3.5账户无法获取har文件，0.7.2会报500错误

**Comment by gngpp** [comment]
> @gngpp 更新到0.7.2后原问题已解决。但是未灰度的3.5账户无法获取har文件，0.7.2会报500错误

自己上传就行了，迟早全部灰度，你没有上传就报错

**Comment by heurainbow** [comment]
上传别的3.5d的账户的har文件么？
如果har文件可以共享，那一个服务端可以同时支持多个账户？

**Comment by gngpp** [comment]
har跟账号没有任何关系，只是一个浏览器的特征
