### ISSUE TITLE
funcaptcha  game_type 3未支持

### ISSUE THREAD

**Issue by wu1724** [gngpp/ninja#220]
![image](https://github.com/gngpp/ninja/assets/75959073/fac4928b-7587-45f6-bb6b-28e974a26e7a)
funcaptcha的game_type为3时无法使用

**Comment by gngpp** [comment]
这个是平台解析打的码不对，不是不支持

**Comment by wu1724** [comment]
> 这个是平台解析打的码不对，不是不支持

okok
