### ISSUE TITLE
0.7.2版本 /to/v1/chat/complentions 报错No solver available

### ISSUE THREAD

**Issue by sola97** [gngpp/ninja#221]
退回0.7.1能正常使用，更新到0.7.2我重新上传了chat4的har，仍报错；是我漏更新了什么吗
![image](https://github.com/gngpp/ninja/assets/17388849/c9017414-ea68-4c0a-91d0-13194daa9c26)

**Comment by gngpp** [comment]
重新下载：https://github.com/gngpp/ninja/releases/tag/v0.7.2
