### ISSUE TITLE
报错导致docker自动结束运行

### ISSUE THREAD

**Issue by wu1724** [gngpp/ninja#223]
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', openai/src/arkose/funcaptcha/api_breaker.rs:119:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by gngpp** [comment]
等更完重新下载：https://github.com/gngpp/ninja/releases/tag/v0.7.2
