### ISSUE TITLE
submit funcaptcha answer error: channel closed

### ISSUE THREAD

**Issue by snailq** [gngpp/ninja#228]
请教这个怎么解决？认证过不了，程序指定的yescaptcha
<img width="2128" alt="image" src="https://github.com/gngpp/ninja/assets/14817804/53e89476-ddef-4cc1-8f7a-caca294bad89">
<img width="2200" alt="image" src="https://github.com/gngpp/ninja/assets/14817804/76979fd9-8d40-4472-a6bd-04f3f88e1198">

**Comment by gngpp** [comment]
yescaptcha服务估计被你打崩了，你现在卸载当前程序，重新下载最新的，我配置了国际节点，现在用这个节点延迟比较低

**Comment by gngpp** [comment]
https://github.com/gngpp/ninja/releases/tag/v0.7.3
