### ISSUE TITLE
请问直接请求chatgpt-api可以吗？

### ISSUE THREAD

**Issue by hst-Sunday** [gngpp/ninja#230]
比如在postman发起请求http://localhost:7999/backend-api/conversation
我试了下 返回如下：
body为:
```
 {
        "action": "next",
        "messages": [
            {
                "id": "97a1aae0-c099-4590-a473-f60423f0e27c",
                "author": {
                    "role": "user"
                },
                "content": {
                    "content_type": "text",
                    "parts": [
                        "你好啊"
                    ]
                },
                "metadata": {}
            }
        ],
        "model": "gpt-4",
        "parent_message_id": "396b852d-e6e8-4c61-aecb-23edbacd6aa0",
        "timezone_offset_min": -480,
        "history_and_training_disabled": false
    }
```
response为:
```
{
    "detail": [
        {
            "loc": [
                "body"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```
请问是哪里出了问题吗？还是说不支持这样调用？

**Comment by gngpp** [comment]
你可以抄一下官网网页参数，是缺少字段了

**Comment by dwdcth** [comment]
在启动时还得指定 gpt4的 arkose的har

**Comment by gngpp** [comment]
> 你可以抄一下官网网页参数，是缺少字段了

如果不带上arkose_token字段也无妨，后端帮处理补上了

**Comment by hst-Sunday** [comment]
@gngpp 按照官网的网页参数都加上去了 ，也还是不行😂

**Comment by gngpp** [comment]
不可能，请更新最新版

**Comment by gngpp** [comment]
> 不可能，请更新最新版

官网的arkose_token字段可以不加，但是后端必须上传有特征文件或arkose solver key

**Comment by hst-Sunday** [comment]
![WX20231026-115621@2x](https://github.com/gngpp/ninja/assets/18478530/45810ddd-7773-47d3-858b-f23aa5429378)
@gngpp 从官网保存的chat4.openai.com.har文件上传报这个

**Comment by gngpp** [comment]
> ![WX20231026-115621@2x](https://user-images.githubusercontent.com/18478530/278207461-45810ddd-7773-47d3-858b-f23aa5429378.png) @gngpp 从官网保存的chat4.openai.com.har文件上传报这个

很明显你的文件有问题，抓的不对

**Comment by hst-Sunday** [comment]
@gngpp 感谢啊，上传成功了，可是请求还是不成功，参数除了arkose_token没填，和官网一样了
```
2023-10-26T04:30:58.626727Z  INFO openai::context: HAR file changes observed: /root/.chat4.openai.com.har    
```
```
{
    "detail": [
        {
            "loc": [
                "body"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```

**Comment by gngpp** [comment]
> @gngpp 感谢啊，上传成功了，可是请求还是不成功，参数除了arkose_token没填，和官网一样了
> 
> ```
> 2023-10-26T04:30:58.626727Z  INFO openai::context: HAR file changes observed: /root/.chat4.openai.com.har    
> ```
> 
> ```
> {
>     "detail": [
>         {
>             "loc": [
>                 "body"
>             ],
>             "msg": "field required",
>             "type": "value_error.missing"
>         }
>     ]
> }
> ```

发你的参数过来吧，这是官网返回的错误，很明显就是你的参数有问题

**Comment by hst-Sunday** [comment]
```
{
    "action": "next",
    "messages": [
        {
            "id": "aaa26712-4fd9-4e56-9583-ff095b78321885",
            "author": {
                "role": "user"
            },
            "content": {
                "content_type": "text",
                "parts": [
                    "你好啊"
                ]
            },
            "metadata": {}
        }
    ],
    "conversation_id": "8830f37a-ab55-4704-b393-0f433314f4617",
    "parent_message_id": "2434afd4-372a-46a8-880b-7cfeccb22248",
    "model": "gpt-4",
    "timezone_offset_min": -480,
    "suggestions": [],
    "history_and_training_disabled": false,
    "conversation_mode": {
        "kind": "primary_assistant"
    },
    "force_paragen": false
}
```
我直接复制的官网参数

**Comment by gngpp** [comment]
> > @gngpp 感谢啊，上传成功了，可是请求还是不成功，参数除了arkose_token没填，和官网一样了
> > ```
> > 2023-10-26T04:30:58.626727Z  INFO openai::context: HAR file changes observed: /root/.chat4.openai.com.har    
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > {
> >     "detail": [
> >         {
> >             "loc": [
> >                 "body"
> >             ],
> >             "msg": "field required",
> >             "type": "value_error.missing"
> >         }
> >     ]
> > }
> > ```
> 
> 发你的参数过来吧，这是官网返回的错误，很明显就是你的参数有问题，除此之外，GPT-4还需要_puid作为cookie发送 GPT-3.5正常是这样:
> 
> ```json
> {
>     "action": "next",
>     "messages": [
>         {
>             "id": "aaa28b31-2640-4e48-8d29-6c234a4871fd",
>             "author": {
>                 "role": "user"
>             },
>             "content": {
>                 "content_type": "text",
>                 "parts": [
>                     "rust examples"
>                 ]
>             },
>             "metadata": {}
>         }
>     ],
>     "parent_message_id": "ecebb375-69a2-4e7a-ba42-b22ba5c9cfbe",
>     "model": "gpt-3.5",
>     "timezone_offset_min": -480,
>     "suggestions": [],
>     "history_and_training_disabled": true
> }
> ```

如果不是开发对接客户端，我劝你不要乱来，老老实实用其他人做好UI或者用自带的

**Comment by hst-Sunday** [comment]
@gngpp 感谢大佬耐心解答

**Comment by hst-Sunday** [comment]
@gngpp 大佬 我试了下3.5的，也是这个报错😂
