### ISSUE TITLE
GPT4 error

### ISSUE THREAD

**Issue by heurainbow** [gngpp/ninja#231]
WARN openai::serve: [openai/src/serve/mod.rs:656:13] Check IP request error: error sending request for url (https://ifconfig.me/): error trying to connect: TLS handshake failed: cert verification failed - Invalid certificate verification context unexpected EOF

这个是什么问题，早上还没有这个问题，后来开始429错误，然后重新部署就会出现这个错误

**Comment by gngpp** [comment]
你网络G了

**Comment by GeekWorkCode** [comment]
你好！我有点疑问，配置warp就是解决自己的ip被封了的问题，为啥配置了warp还是会提示这个ip错误，这个地方是不能走warp代理吗？
