### ISSUE TITLE
启动报错error: unrecognized subcommand 'serve'

### ISSUE THREAD

**Issue by redstarxz** [gngpp/ninja#233]
docker-compose 0.7.3版本，启动

watchtower  | time="2023-10-26T08:37:37Z" level=info msg="Watchtower 1.6.0"
watchtower  | time="2023-10-26T08:37:37Z" level=info msg="Using no notifications"
watchtower  | time="2023-10-26T08:37:37Z" level=info msg="Checking all containers (except explicitly disabled with label)"
watchtower  | time="2023-10-26T08:37:37Z" level=info msg="Scheduling first run: 2023-10-26 09:37:37 +0000 UTC"
watchtower  | time="2023-10-26T08:37:37Z" level=info msg="Note that the first check will be performed in 59 minutes, 59 seconds"
ninja       | error: unrecognized subcommand 'serve'

**Comment by gngpp** [comment]
去掉serve
