### ISSUE TITLE
No solver available

### ISSUE THREAD

**Issue by Nothingness-Void** [gngpp/ninja#235]
服务使用的是 ：https://github.com/lss233/chatgpt-mirai-qq-bot
har文件已上传
![image](https://github.com/gngpp/ninja/assets/55913486/a53fb064-ec10-4259-83f2-7a4d099fad35)
通过本项目自带的web-ui可以登录并正常聊天
![image](https://github.com/gngpp/ninja/assets/55913486/96855cb3-3fe3-4f2e-b041-3e287e6353c3)
服务请求的接口是 https:xxx/backend-api/conversation
还请大佬帮忙看看

**Comment by xiaonian233** [comment]
有相同情况
直接在网页上提问要先过验证码才行，我猜应该是验证码导致的

**Comment by gngpp** [comment]
可以给演示站上传HAR特征试试，演示站基本没怎么出过码，人少用，https://ninja-yu6f.onrender.com/har/upload

**Comment by spammenotinoz** [comment]
I find it best to download the har while ChatGPT is responding.
ie: Ask a complex prompt.

**Comment by gngpp** [comment]
> I find it best to download the har while ChatGPT is responding. ie: Ask a complex prompt.

I agree

**Comment by xiaonian233** [comment]
换了一个ip抓har正常可用
尝试了接入yescaptcha配置正确后出现
`错误的问题ID，如果您没有填写错误，可能是这个问题暂时还不支持，请联系客服（新问题3工作日内会得到支持`
不知道是没训练模型还是什么情况

**Comment by gngpp** [comment]
应该是了，有人出图很变态

**Comment by Nothingness-Void** [comment]
> 换了一个ip抓har正常可用 尝试了接入yescaptcha配置正确后出现 `错误的问题ID，如果您没有填写错误，可能是这个问题暂时还不支持，请联系客服（新问题3工作日内会得到支持` 不知道是没训练模型还是什么情况

感谢 我去试试

**Comment by Nothingness-Void** [comment]
> > 换了一个ip抓har正常可用 尝试了接入yescaptcha配置正确后出现 `错误的问题ID，如果您没有填写错误，可能是这个问题暂时还不支持，请联系客服（新问题3工作日内会得到支持` 不知道是没训练模型还是什么情况
> 
> 感谢 我去试试

换Ip并问复杂问题抓的har确实有用 感谢各位

**Comment by Alauda95** [comment]
我配置了实例自动刷公网IP，不用重启，AWS EC2，有一次刷码个数达到5个，换IP就没了。

**Comment by gngpp** [comment]
有条件的可以试试ipv6，随机IP池，整一段子网带上启动参数 --ipv6-subnet xxxx:xxxx:xxxx::/48

**Comment by heurainbow** [comment]
@gngpp 500报错后，后台还会出现把cpu占满的情况，这是为什么？是否可以自动停止？

**Comment by heurainbow** [comment]
多线程，每个线程单个静态IP代理+单个账户har特征，目前比较稳定

**Comment by gngpp** [comment]
> @gngpp 500报错后，后台还会出现把cpu占满的情况，这是为什么？是否可以自动停止？

监控截图呢，日志也发来

**Comment by heurainbow** [comment]
> > @gngpp 500报错后，后台还会出现把cpu占满的情况，这是为什么？是否可以自动停止？
> 
> 监控截图呢，日志也发来

![未命名1698580796](https://github.com/gngpp/ninja/assets/6753276/95d7816a-60e9-41b6-9bf7-4cc57c39511f)
![未命名1698580730](https://github.com/gngpp/ninja/assets/6753276/25dba0f8-f804-4027-bdf3-a5dfdee73804)

同样的账户和代理，重启一下就会正常。

**Comment by gngpp** [comment]
> > > @gngpp 500报错后，后台还会出现把cpu占满的情况，这是为什么？是否可以自动停止？
> > 
> > 
> > 监控截图呢，日志也发来
> 
> ![未命名1698580796](https://user-images.githubusercontent.com/6753276/278869506-95d7816a-60e9-41b6-9bf7-4cc57c39511f.png) ![未命名1698580730](https://user-images.githubusercontent.com/6753276/278869509-25dba0f8-f804-4027-bdf3-a5dfdee73804.png)
> 
> 同样的账户和代理，重启一下就会正常。

latency 100000+ ms，你网络也太烂了，后台等待估计爆了，把超时时间弄短点，默认10分钟，连接超时也弄短点
