### ISSUE TITLE
warp not supported arm linux/arm64/v8

### ISSUE THREAD

**Issue by yexueduxing** [gngpp/ninja#238]
warp The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested。

**Comment by yexueduxing** [comment]
warp 目前不支持arm架构，导致ninja如果要使用warp代理的话无法启动，后边是否考虑增加warp镜像的arm架构支持？

**Comment by gngpp** [comment]
warp你可以看看官方有没有支持，不支持的话我也没办法

**Comment by baby9** [comment]
Warp do not support arm architecture officially. In general, we use wgcf (wireguard protocol connect to warp) instead, you may try wireguard over socks or http proxy
