### ISSUE TITLE
ChatGPT to API : 根据accessToken生成API Key

### ISSUE THREAD

**Issue by muxinxy** [gngpp/ninja#240]
使用 ChatGPT to API 的时候，直接使用 accessToken 有风险，而且长度过大。请问是否可以根据 accessToken 生成更短的 API Key ？

**Comment by gngpp** [comment]
后续再支持吧，只不过要维护一份token缓存

**Comment by We1eVen** [comment]
用[oneapi](https://github.com/songquanpeng/one-api)转一下就行，但要注意暂时不能用mysql，key值长度会溢出

**Comment by gngpp** [comment]
https://github.com/songquanpeng/one-api
