### ISSUE TITLE
chatgpt next web怎么接入这个项目呢

### ISSUE THREAD

**Issue by sunjice** [gngpp/ninja#241]
chatgpt next web怎么接入这个项目呢？
我配置的是：BASE_URL= http://host:7999/to
但是好像不起作用

**Comment by xiaonian233** [comment]
![image](https://github.com/gngpp/ninja/assets/21072615/3305ce7b-4d5c-43e7-b4e6-1ee230c16b23)

**Comment by spammenotinoz** [comment]
http://host:7999/backend-api/
