### ISSUE TITLE
大佬好。 最近用账号密码登录会 502

### ISSUE THREAD

**Issue by mygit-2023** [gngpp/ninja#242]
浏览器调用这个 https://tcr9i.chat.openai.com/fc/a/?callback=  
Post 回跳到  /auth/login   然后 502了。

**Comment by gngpp** [comment]
开debug日志发我看看，warn可以不用理

**Comment by gngpp** [comment]
没什么应该是网络有问题 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

**Comment by mygit-2023** [comment]
ninja         | 2023-10-30T02:12:55.409388Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}: reqwest_impersonate::async_impl::client: redirect policy disallowed redirection to 'https://chat.openai.com/api/auth/callback/auth0?code=DVq9PQ1ORQEX3avQ9GwWak94OvOis1DCz0aV8GHPL1muR&state=X7FeajuHHzh1dw0nUFUJZNHLBgh2CDLRHb2xN_ztYx8'
ninja         | 2023-10-30T02:12:55.409445Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}: openai::auth: [openai/src/auth/mod.rs:247:9] get_location_path: {"date": "Mon, 30 Oct 2023 02:12:55 GMT", "content-type": "text/plain; charset=utf-8", "content-length": "170", "location": "https://chat.openai.com/api/auth/callback/auth0?code=DVq9PQ1ORQEX3avQ9GwWak94OvOis1DCz0aV8GHPL1muR&state=X7FeajuHHzh1dw0nUFUJZNHLBgh2CDLRHb2xN_ztYx8", "cf-cache-status": "DYNAMIC", "cache-control": "no-store, max-age=0, no-transform", "set-cookie": "auth0=s%3AEiSiLaocOZch6iSSXfYUb7-k0eiPkJ-A.3hTK%2FciDAf1M5WJBJcyjosw9Kp%2BayqhS2d6JvH04r8o; Path=/; Expires=Mon, 13 Nov 2023 02:12:55 GMT; HttpOnly; Secure; SameSite=None", "set-cookie": "auth0_compat=s%3AEiSiLaocOZch6iSSXfYUb7-k0eiPkJ-A.3hTK%2FciDAf1M5WJBJcyjosw9Kp%2BayqhS2d6JvH04r8o; Path=/; Expires=Mon, 13 Nov 2023 02:12:55 GMT; HttpOnly; Secure", "strict-transport-security": "max-age=31536000; includeSubDomains; preload", "vary": "Accept, Accept-Encoding", "ot-baggage-auth0-request-id": "81e022d40cd47e77", "ot-tracer-sampled": "true", "ot-tracer-spanid": "19ebb45a4c771390", "ot-tracer-traceid": "57cb4983624dd547", "pragma": "no-cache", "traceparent": "00-000000000000000057cb4983624dd547-19ebb45a4c771390-01", "tracestate": "auth0-request-id=81e022d40cd47e77,auth0=true", "x-auth0-requestid": "002278a26a8212fdaa8d", "x-content-type-options": "nosniff", "x-ratelimit-limit": "10000", "x-ratelimit-remaining": "9999", "x-ratelimit-reset": "1698631976", "server": "cloudflare", "cf-ray": "81e022d40cd47e77-LAX"}
ninja         | 2023-10-30T02:12:55.409502Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}: hyper_imp::client::pool: reuse idle connection for ("https", chat.openai.com)
ninja         | 2023-10-30T02:12:55.409550Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_write: send frame=Headers { stream_id: StreamId(5), flags: (0x5: END_HEADERS | END_STREAM) }
ninja         | 2023-10-30T02:12:55.449980Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_read: received frame=Data { stream_id: StreamId(9) }
ninja         | 2023-10-30T02:12:55.450062Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_read: received frame=Data { stream_id: StreamId(9), flags: (0x1: END_STREAM) }
ninja         | 2023-10-30T02:12:55.664773Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_read: received frame=Headers { stream_id: StreamId(5), flags: (0x5: END_HEADERS | END_STREAM) }
ninja         | 2023-10-30T02:12:55.664898Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}: reqwest_impersonate::async_impl::client: redirect policy disallowed redirection to 'https://chat.openai.com/'
ninja         | 2023-10-30T02:12:55.664990Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}: hyper_imp::client::pool: reuse idle connection for ("https", chat.openai.com)
ninja         | 2023-10-30T02:12:55.665047Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_write: send frame=Headers { stream_id: StreamId(7), flags: (0x5: END_HEADERS | END_STREAM) }
ninja         | 2023-10-30T02:12:55.729907Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_read: received frame=Headers { stream_id: StreamId(7), flags: (0x4: END_HEADERS) }
ninja         | 2023-10-30T02:12:55.769874Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_read: received frame=Data { stream_id: StreamId(7) }
ninja         | 2023-10-30T02:12:55.769913Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}:Connection{peer=Client}: h2_imp::codec::framed_read: received frame=Data { stream_id: StreamId(7), flags: (0x1: END_STREAM) }
ninja         | 2023-10-30T02:12:55.770193Z DEBUG request{method=POST uri=/auth/login version=HTTP/1.0}: tower_http::trace::on_response: finished processing request latency=1997 ms status=303
ninja         | 2023-10-30T02:12:55.770269Z DEBUG hyper::proto::h1::io: flushed 5273 bytes
ninja         | 2023-10-30T02:13:03.343250Z DEBUG hyper_imp::client::client: client connection error: connection error: connection closed because of a broken pipe
ninja         | 2023-10-30T02:13:05.426271Z DEBUG hyper_imp::client::client: client connection error: connection error: connection closed because of a broken pipe
ninja         | 2023-10-30T02:13:05.735505Z DEBUG hyper_imp::client::client: client connection error: connection error: connection closed because of a broken pipe


---
用 Access token 登录是正常的， 用帐号密码登录会报  502

**Comment by mygit-2023** [comment]
![image](https://github.com/gngpp/ninja/assets/128624873/1a9b8989-5604-46d6-8f11-8b7b9a94b2cd)

**Comment by gngpp** [comment]
你的IP废了，换IP吧，我有一台机子就是不能登录，但是可以访问会话

**Comment by gngpp** [comment]
> 你的IP废了，换IP吧，我有一台机子就是不能登录，但是可以访问会话

openai对登录限制很严格

**Comment by mygit-2023** [comment]
嗯，我看演示站是正常的  。 您的 login 是 303 。我的是 502 。 我用的 Warp 。重启换 ip 么。。
![image](https://github.com/gngpp/ninja/assets/128624873/dac5d70b-aceb-4503-bc99-890bd440d432)

**Comment by gngpp** [comment]
> 嗯，我看演示站是正常的 。 您的 login 是 303 。我的是 502 。 我用的 Warp 。重启换 ip 么。。 ![image](https://user-images.githubusercontent.com/128624873/278922275-dac5d70b-aceb-4503-bc99-890bd440d432.png)

不一定会换，谷歌我记得有个教程教怎么重启换warp IP的，你可以去试试

**Comment by mygit-2023** [comment]
大佬，同样的环境，我用ninjia的auth界面，通过账号密码获取access token 是正常的，先用这种方式顶一下了😃

**Comment by gngpp** [comment]
> 大佬，同样的环境，我用ninjia的auth界面，通过账号密码获取access token 是正常的，先用这种方式顶一下了😃

没有这种说法，两个接口调用的代码都是一样
