### ISSUE TITLE
关于使用gpt3.5还是gpt4的疑问

### ISSUE THREAD

**Issue by snailq** [gngpp/ninja#244]
请教大神
前端使用的是chatgpt-next-web
配置的BASE_URL="http://*:7999/to"(这个项目好像只能使用这个api，backend-api不能使用)

我有两个账号一个开通了plus，另一个没有，但是有open api gpt4的权限
而分别使用两个账号的accesstoken时,都可以使用gpt4

看项目特征有一条：“API密钥获取”，是项目支持通过accesstoken获取openai的key而通过api去访问的gpt4？

**Comment by gngpp** [comment]
openai api是官方出的API，用到key访问。跟access token网页版的API不一样，不要搞混了
