### ISSUE TITLE
运行 examples/chatgpt.rs  报错

### ISSUE THREAD

**Issue by dlxj** [gngpp/ninja#246]
请教，怎样才能正常运行

```Error: error sending request for url (https://chat.openai.com/backend-api/models): error trying to connect: TLS handshake failed: cert verification failed - unable to get local issuer certificate [CERTIFICATE_VERIFY_FAILED]

Caused by:
    0: error trying to connect: TLS handshake failed: cert verification failed - unable to get local issuer certificate [CERTIFICATE_VERIFY_FAILED]
    1: TLS handshake failed: cert verification failed - unable to get local issuer certificate [CERTIFICATE_VERIFY_FAILED]
    2: [CERTIFICATE_VERIFY_FAILED]
    3: [CERTIFICATE_VERIFY_FAILED]```

**Comment by gngpp** [comment]
> 请教，怎样才能正常运行
> 
> ```
> 
> Caused by:
>     0: error trying to connect: TLS handshake failed: cert verification failed - unable to get local issuer certificate [CERTIFICATE_VERIFY_FAILED]
>     1: TLS handshake failed: cert verification failed - unable to get local issuer certificate [CERTIFICATE_VERIFY_FAILED]
>     2: [CERTIFICATE_VERIFY_FAILED]
>     3: [CERTIFICATE_VERIFY_FAILED]```
> ```

你跑example干嘛，很久没测试了
