### ISSUE TITLE
默认Web端，使用账密登录需要做题然后提示invalid Location，Access Token则没问题

### ISSUE THREAD

**Issue by tyhunter** [gngpp/ninja#248]
好奇是目前普遍存在的问题，还是说我这而是个例？

**Comment by gngpp** [comment]
invalid location 是跳转到首页去了，说明你的网络有问题IP不干净，openai对登录比发会话限制更高，我的机子跟演示站没有任何问题

**Comment by tyhunter** [comment]
感谢，我是搭配WARP使用，先用第三方面板和Token能解决就先不折腾了

**Comment by gngpp** [comment]
> 感谢，我是搭配WARP使用，先用第三方面板和Token能解决就先不折腾了

warp就更加了，不差钱可以买个LA的机子都能随便访问了

**Comment by tyhunter** [comment]
嗯嗯，明白了，感谢大佬
