### ISSUE TITLE
出现这样的错误： '{"code":"403","msg":"HTTP status client error (403 Forbidden) for url (https://chat.openai.com/backend-api/conversation)"}' 

### ISSUE THREAD

**Issue by tianlichunhong** [gngpp/ninja#249]
在某厂的vps均出现这样的错误。
**我的docker-compose配置如下：**
`version: '3'
services:
    ninja:
        image: ghcr.io/gngpp/ninja:latest
        container_name: ninja
        restart: unless-stopped
        environment:
          - TZ=Asia/Shanghai
          - PROXY=socks5://xxxxx:1080
        volumes:
          - ${PWD}/har:/root
          - ${PWD}/serve.toml:/serve.toml
        ports:
          - 7999:7999       
        command: run --arkose-chat3-har-file /root/chat.openai.com.har

    watchtower:
        container_name: ninja_watchtower
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 3600 --cleanup
        restart: unless-stopped`
**该配置在甲骨文的vps是正常运行的。在该厂的vps也正常启动。启动日志如下：**
`Attaching to ninja_watchtower, ninja
ninja         | 2023-11-03T01:28:55.886580Z  INFO openai::serve: Starting HTTP(S) server at http(s)://0.0.0.0:7999
ninja         | 2023-11-03T01:28:55.886618Z  INFO openai::serve: Starting 1 workers
ninja         | 2023-11-03T01:28:55.886624Z  INFO openai::serve: Concurrent limit 65535
ninja         | 2023-11-03T01:28:55.886627Z  INFO openai::serve: Enabled cookie store: false
ninja         | 2023-11-03T01:28:55.886631Z  INFO openai::serve: Keepalive 60 seconds
ninja         | 2023-11-03T01:28:55.886635Z  INFO openai::serve: Timeout 600 seconds
ninja         | 2023-11-03T01:28:55.886638Z  INFO openai::serve: Connect timeout 60 seconds
ninja         | 2023-11-03T01:28:55.965746Z  INFO openai::serve: What is my IP address: XXXXXXX
watchtower_1  | time="2023-11-03T01:28:56Z" level=info msg="Watchtower 1.6.0"
watchtower_1  | time="2023-11-03T01:28:56Z" level=info msg="Using no notifications"
watchtower_1  | time="2023-11-03T01:28:56Z" level=info msg="Checking all containers (except explicitly disabled with label)"
watchtower_1  | time="2023-11-03T01:28:56Z" level=info msg="Scheduling first run: 2023-11-03 02:28:56 +0000 UTC"
watchtower_1  | time="2023-11-03T01:28:56Z" level=info msg="Note that the first check will be performed in 59 minutes, 59 seconds"`
**然后客户端的python脚本如下：**
`import openai
access_token="XXXXXX"
openai.api_key =access_token
openai.api_base = "http://127.0.0.1:7999/to/v1"

while True:
    text = input("请输入问题：")
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {'role': 'user', 'content': text},
        ],
        stream=True,
    )

    for chunk in response:
        print(chunk.choices[0].delta.get("content", ""), end="", flush=True)
    print("\n")
`
**然后就出现这样的错误：**
`Traceback (most recent call last):
  File "/root/ninja/test.py", line 13, in <module>
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.11/dist-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"code":"403","msg":"HTTP status client error (403 Forbidden) for url (https://chat.openai.com/backend-api/conversation)"}' (HTTP response code was 403)`

如果将接入地址改成http://127.0.0.1:7999/v1，通过API的方式接入，是正常使用的。
docker脚本中的代理PROXY=socks5://xxxxx:1080指向一个可以正常使用ninja的甲骨文vps。所以也不应该是IP地址的问题。不管是否设置代理，或者代理使用wrap。都是同样的错误返回。请问这是什么原因？或者如何查找原因？har文件是正确的。同样的脚本，同样的配置，在甲骨文vps上正常运行。

**Comment by gngpp** [comment]
走代理，又是没关闭直连？--disable-direct
