### ISSUE TITLE
docker安装出现报错exec /bin/bash: exec format error

### ISSUE THREAD

**Issue by shangguo3** [gngpp/ninja#251]
warp:
    container_name: warp
    image: ghcr.io/gngpp/warp:latest
    restart: unless-stopped
日志提示报错
exec /bin/bash: exec format error

**Comment by gngpp** [comment]
什么平台

**Comment by gngpp** [comment]
除了x86 其他平台都不支持warp

**Comment by shangguo3** [comment]
ARM 架构的

**Comment by gngpp** [comment]
那就是不支持
