### ISSUE TITLE
新版本 会出现 No solver available，har已上传

### ISSUE THREAD

**Issue by xixi-furry** [gngpp/ninja#252]
RT，顺便想了解一下，什么情况下会出现 No solver available？

**Comment by gngpp** [comment]
新版本需要重新上传

**Comment by xixi-furry** [comment]
之前版本的我也已经移过去了，包括目录也重新映射了，看upload里已经有之前的了，是还是需要重新上传一下让后端来处理么？

**Comment by gngpp** [comment]
你先看看上传页面有没有读到文件了

**Comment by xixi-furry** [comment]
有
![IMG_1447](https://github.com/gngpp/ninja/assets/59167815/80941512-2f38-43e1-b327-d8f3bb2c9105)

**Comment by gngpp** [comment]
等会修复

**Comment by xixi-furry** [comment]
好的，辛苦您了

**Comment by xixi-furry** [comment]
另外一个就是我看到似乎这个dir的参数没有获取env里的，可以设置成获取env里的参数来作为dir目录么？

**Comment by gngpp** [comment]
没必要用env，ninja gt 生成一份serve.toml配置模版，然后填好需要参数，启动直接读配置，ninja run -C serve.toml

**Comment by gngpp** [comment]
https://github.com/gngpp/ninja/actions/runs/6744032256
