### ISSUE TITLE
打扰一下，由于我抓的har包传上去了（已经在网页上显示上传上去了）还是会跳验证，我想问一下我的har包是不是抓的有问题

### ISSUE THREAD

**Issue by xiaosaaaa** [gngpp/ninja#256]
我抓包的时候找不到这个har包https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147
我抓到的包名是https://tcr9i.chat.openai.com/fc/gt2/public_key/3D86FBBA-9D22-402A-B512-3420086BA6CC
这样会有问题吗？
ps:：我是用gpt3.5的账户抓的

**Comment by gngpp** [comment]
要看你发什么了，正常来说，需要抓登录、gpt3.5、gpt4，每个类型的验证码都不一样的

**Comment by xiaosaaaa** [comment]
嗯嗯，登录的过程还有我进行了一句对话的包我应该都抓到了，我想过的是arkose的验证码，但是我上传了还是不行，拿您这边的演示站试了试还是会跳验证码，不知道哪里除了问题。

**Comment by gngpp** [comment]
> 嗯嗯，登录的过程还有我进行了一句对话的包我应该都抓到了，我想过的是arkose的验证码，但是我上传了还是不行，拿您这边的演示站试了试还是会跳验证码，不知道哪里除了问题。

你不要想太多，特征不是百分百不出码，现在号商都在撞号，openai登录封控又拉高了

**Comment by xiaosaaaa** [comment]
好的明白了，感谢。
