### ISSUE TITLE
Using Ninja's web API in chatgpt-web, error!

### ISSUE THREAD

**Issue by 3tel** [gngpp/ninja#270]
Using Ninja's web API(http://host:port/to/v1/chat/completions) in chatgpt-web, it prompts "ChatGPT error 422: Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: map, expected a string at line 1 column 98"

**Comment by 3tel** [comment]
ChatGPTError: ChatGPT error 422: Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: map, expected a string at line 1 column 98
    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 422,
  statusText: 'Unprocessable Entity',
  [cause]: _Response [Response] {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 422,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Unprocessable Entity',
      headersList: [_HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: _HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by gngpp** [comment]
Please click star before asking a question
