### ISSUE TITLE
chatgpt官方ui 部分用户已更新，导致代理ui无法正常使用

### ISSUE THREAD

**Issue by shefvic** [gngpp/ninja#272]
我的账户在https://chat.openai.com 的UI 今天更新了，然后ninja的代理服务UI已无法正常使用：

chatgpt官方：  
![image](https://github.com/gngpp/ninja/assets/130276872/6989bbdb-4bee-46b3-8935-e5d43cc4b2f8)

ninja 代理ui:  
![image](https://github.com/gngpp/ninja/assets/130276872/8fc2ab76-5084-49c6-8436-35129c649c46)

**Comment by muxinxy** [comment]
登录报错
`failed get csrf token`
后台报错
`ERROR tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=73 ms`

**Comment by gngpp** [comment]
登录已经死了，可以用warp顶一下，csrf拿不到就是被ban IP了，我几台机子的机房IP都被ban了。然而UI并没有问题
<img width="1711" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/da7412db-07bd-4b8d-b623-74b4d8882c06">

**Comment by Alauda95** [comment]
AWS EC2全军覆没，怎么改IP都没用；去ChatGPT老家（Azure）部署了Ninja。

**Comment by shefvic** [comment]
也可能和昨天openai全服务的重大中断有关： https://status.openai.com/ 
现在已经恢复了。  

---

现在ninja的代理ui可以正常访问了，但是样式还是旧版界面：
![image](https://github.com/gngpp/ninja/assets/130276872/5e6f79fa-056d-4a8f-906e-5df95a172464)
并且这些下拉选项的功能似乎已失效，比如选择dalle3也不会生成图像，而是文字回复。 

chatgpt的官方界面：
![image](https://github.com/gngpp/ninja/assets/130276872/b9eb0e6f-25ff-4748-ab00-c183051aa773)

但新版界面和功能openai暂时还没有对所有用户开放，猜测对旧版界面的用户没有影响

**Comment by heurainbow** [comment]
![image](https://github.com/gngpp/ninja/assets/6753276/13398011-3e6f-453c-bd6f-fbbb30773a84)

http 403 报错，尝试换ip也没有作用。 有什么解决办法?

**Comment by shefvic** [comment]
@heurainbow 现在chatgpt官方服务又挂了

**Comment by heurainbow** [comment]
官方web页面登陆是正常的。
PS 切换到azure也是一样的。

**Comment by Alauda95** [comment]
Azure上午能用，下午挂了，试了美东和日南

**Comment by heurainbow** [comment]
我也是上午能用（非azure）

**Comment by Alauda95** [comment]
目前一切正常，AWS EC2又能用了。0.8.0。

**Comment by heurainbow** [comment]
代理页面目前还是老版页面而不是新版页面，官方页面是新版页面，如何解决
