### ISSUE TITLE
昨天openai更新后，ChatGPT-To-API的gpt4不能使用了

### ISSUE THREAD

**Issue by snailq** [gngpp/ninja#274]
昨天openai更新后，chatgpt-to-api的gpt4不能使用了，3.5 正常，前端用的ChatGPT-Next-Web
debug log 如下，没返回 ，不知道哪里的问题，大佬帮看看
<img width="2612" alt="image" src="https://github.com/gngpp/ninja/assets/14817804/d8f60413-0e8a-4641-9a6e-f064e63ed943">

**Comment by gngpp** [comment]
4.0的har有没有上传

**Comment by snailq** [comment]
传了 ，还不放心 重新下载 重新传试了也不行
chatgpt-web这个项目和本项目的web  用 backend-api时，3.5和4都能正常用

**Comment by gngpp** [comment]
昨天重构搞出问题了，等重新发版:https://github.com/gngpp/ninja/actions/runs/6797396581
