### ISSUE TITLE
使用ChatGPT to API 报错，大佬这是什么原因?

### ISSUE THREAD

**Issue by dumbsheep1990** [gngpp/ninja#278]
使用ChatGPT to API 报500 错误
{
    "code": "500",
    "msg": "No solver available"
}

**Comment by dumbsheep1990** [comment]
貌似是har文件的问题，har文件有什么具体的要求么?

**Comment by dumbsheep1990** [comment]
现在可以发送请求，但是返回都为空。

**Comment by gngpp** [comment]
图呢？日志呢？用什么客户端？什么版本？发的什么模型？

**Comment by gngpp** [comment]
![Screenshot_2023-11-09-06-30-59-452_com.android.browser.jpg](https://github.com/gngpp/ninja/assets/51810656/2063bcaa-d958-498c-9d6c-50d745730033)

**Comment by dumbsheep1990** [comment]
docker 0.7.9版本， postman模拟![image](https://github.com/gngpp/ninja/assets/123633472/e20d7bed-a14f-478e-9d92-2fdab029852b)

**Comment by gngpp** [comment]
上传HAR特征文件啊，看文档
