### ISSUE TITLE
遇到 Internal Server Error

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [gngpp/ninja#282]
log信息：2023-11-09T09:21:49.055818Z  WARN request{method=POST uri=/backend-api/conversation version=HTTP/1.1}: tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=49 ms

docker-compose配置：
version: '3'

services:
  app:
    # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    image: chenzhaoyu94/chatgpt-web:latest
    restart: unless-stopped
    ports:
      - 6556:3002
    environment:
      # 二选一
      #OPENAI_API_KEY: sk-xxx
      # 二选一
      OPENAI_ACCESS_TOKEN: "TOKEN"
      #API模型，可选，设置 OPENAI_API_KEY 时可用
      #OPENAI_API_MODEL: xxx
      # 每小时最大请求次数，可选，默认无限
      #MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 100000
      API_REVERSE_PROXY: "http://ninja:7999/backend-api/conversation"
    depends_on:
      - ninja

  ninja:
    container_name: ninja
    image: ghcr.io/gngpp/ninja:latest
    ports:
      - 8080:7999
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    command: run

使用洛杉矶的VPS，可正常curl到openai官网

**Comment by gngpp** [comment]
兄弟，openai被ddos了，别开issue了，官网都炸了
#272

**Comment by GitHubChrisChen8035** [comment]
> 兄弟，openai被ddos了，别开issue了，官网都炸了 #272

感谢提醒！！
