### ISSUE TITLE
人机图形验证码验证完之后显示502

### ISSUE THREAD

**Issue by ludashi2020** [gngpp/ninja#286]
![](https://img1.dd.ci/file/4323dd499ed0a0319a470.png)

**Comment by ludashi2020** [comment]
nginx反向代理就出现这个，不用nginx代理不会出现

**Comment by ludashi2020** [comment]
nginx反向代理就出现这个，不用nginx代理不会出现

**Comment by debug-zishou** [comment]
我想问一下这个问题怎么解决的，我也出现了这个问题

**Comment by chenxinstepone** [comment]
nginx设置问题，我的也出现这个问题了，查看日志以后发现是nginx缓存设置不够造成的，nginx里设置就好了，具体问gpt
