### ISSUE TITLE
No solver available，har已上传

### ISSUE THREAD

**Issue by ludashi2020** [gngpp/ninja#288]
版本0.8.0
对话出现`Something went wrong. If this issue persists please contact us through our help center at help.openai.com.`
![](https://img1.dd.ci/file/e85598336ca587d5f021e.png)
返回值：`{"code":"500","msg":"No solver available"}`
![](https://img1.dd.ci/file/5a85d8fc957bcb6cb31ab.png)

**Comment by ludashi2020** [comment]
直接在官网上提问，是正常的。![](https://img1.dd.ci/file/4b2b6cdc8b79b52f08c03.png)

**Comment by gngpp** [comment]
启动参数你怎么写的？

**Comment by ludashi2020** [comment]
> 启动参数你怎么写的？还有GPT-3.5现在也不需要HAR了

我的启动参数如下：`./ninja run --bind 0.0.0.0:8019 --tls-cert /home/wwwroot/ninja/ssl/ssl.cer --tls-key /home/wwwroot/ninja/ssl/ssl.key --arkose-auth-har-dir /home/wwwroot/ninja/auth --arkose-gpt3-har-dir /home/wwwroot/ninja/gpt3 --arkose-gpt4-har-dir /home/wwwroot/ninja/gpt4 --arkose-gpt3-experiment`

**Comment by gngpp** [comment]
--arkose-gpt3-experiment 去掉，这个是后面arkose上线用的

**Comment by ludashi2020** [comment]
> --arkose-gpt3-experiment 去掉，这个是后面arkose上线用的

好的，我试试

**Comment by ludashi2020** [comment]
> --arkose-gpt3-experiment 去掉，这个是后面arkose上线用的

感谢，去掉这个参数之后，就正常了。
