### ISSUE TITLE
API用3.5提示被阻止

### ISSUE THREAD

**Issue by rqt6688** [gngpp/ninja#301]
想用API对接web share
面版上可以看到部分回复，但是几个词语后就停止了
有试过在/har/upload上传har好像没有作用

日志显示：
2023/11/16 02:10:58.635  WARNING: [cws.api.routers.chat]	Field missing. Details: {'conversation_id': '473d7655-501e-411f-9421-471eea6c5844', 'message_id': 'dc7be144-cd77-4e71-aed1-f836b31d379b', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-8LEdnZk3HCcVrkyFYgojuwDLepmy4'}}
2023/11/16 02:10:58.636    DEBUG: [cws.api.routers.chat]	terminated ask 473d7655-501e-411f-9421-471eea6c5844 (ChatModels.default) because of error

**Comment by gngpp** [comment]
这跟我的程序没有关系，自带网页一切正常
