### ISSUE TITLE
auth的包问题请教

### ISSUE THREAD

**Issue by zhangsan2lisi** [gngpp/ninja#302]
请问作者auth的har是chatgpt登录的时候发的包吗？
![image](https://github.com/gngpp/ninja/assets/4944818/d535296d-39dc-4ae5-acd3-cfd8315d8cf7)
![image](https://github.com/gngpp/ninja/assets/4944818/6fe2376f-b5e6-4806-953c-1aa6d9bfb95b)
设置了无效，
![image](https://github.com/gngpp/ninja/assets/4944818/3138ecb9-53c3-4c65-b9ac-4469b7d073ae)
日志提示har包编码错误，还请指教下 auth的包是在哪里下载的

**Comment by gngpp** [comment]
编码错误就换浏览器重新提，正常是不会有问题的
