### ISSUE TITLE
旧的har4可以用，新抓取的无论如何也用不了。。。

### ISSUE THREAD

**Issue by eureka6** [gngpp/ninja#303]
前端`chatgpt-web-share`在国内，后端`ninja`在国外冷门地区的vps上，正常解锁访问openai。

没更新前只是今天开始无法上传文件了（3.5一直用不了，即使上传了har3.5），于是就更新了ninja，然后重新抓了har4和access_token。

结果像往常一样更新完，再用`chatgpt-web-share`去访问ninja，无论旧对话还是新建对话，都是500报错。。。

本以为是cdn.oaistatic.com 这玩意前端访问不了，结果全换成国外vps也是一样500报错

静待大佬修复

**Comment by gngpp** [comment]
arkose做手脚了，暂时没法解决

**Comment by linyours** [comment]
@eureka6 旧的还能用? 我早上抓的har一直500....

**Comment by gngpp** [comment]
不用试了，新的har里边的arkose 特征被做手脚了，有部分非utf8序列，压根不知道是啥玩意

**Comment by linyours** [comment]
完犊子,坐等大佬破解

**Comment by gngpp** [comment]
这回我可能要闭源了，如果能修复的话，因为开源出来很容易被官网盯上，及时修复后续也会被继续搞

**Comment by zhangsan2lisi** [comment]
支持闭源搞，坐等大佬修复

**Comment by gngpp** [comment]
已修复，等重新发版重新下载

**Comment by eureka6** [comment]
> 已修复，等重新发版重新下载

大佬牛波一！！！

**Comment by linyours** [comment]
牛博牛逼

**Comment by zhangsan2lisi** [comment]
> 已修复，等重新发版重新下载

🐂
