### ISSUE TITLE
关于/to/v1/chat/completions上下文token长度问题

### ISSUE THREAD

**Issue by nekomiya-hinata** [gngpp/ninja#304]
使用gpt3.5，在上下文长度达到6-7k这个区间的时候，这个接口时不时会返回`HTTP status client error (413 Payload Too Large) for url (https://chat.openai.com/backend-api/conversation)`的异常，携带的聊天list长度在25左右，这个错误是什么原因呢？

**Comment by gngpp** [comment]
3.5的接口就8k长度啊，25k超几倍了

**Comment by nekomiya-hinata** [comment]
这个25不是指上下文长度，chatgpt正常接口不是有个`messages`的payload么？这个25指的是这个数组的长度，上下文在6-7k应该是没有超过的吧

**Comment by gngpp** [comment]
我咋知道，这是openai限制的消息，只转发不管啊

**Comment by nekomiya-hinata** [comment]
知道了，谢谢
