### ISSUE TITLE
WAPR作为代理，提示ChatGPT can make mistakes. Consider checking important information.

### ISSUE THREAD

**Issue by tyhunter** [gngpp/ninja#306]
最新的版本，用 本地WARP的SOCKS5进行代理，
- PROXIES=socks5://127.0.0.1:40000
还是会出现这个提示：ChatGPT can make mistakes. Consider checking important information.
尝试了清除浏览器缓存和使用无痕模式，都不行

**Comment by gngpp** [comment]
页面的cdn被墙了，你挂梯子访问就行了
