### ISSUE TITLE
webui的一个疑惑

### ISSUE THREAD

**Issue by nekomiya-hinata** [gngpp/ninja#307]
在ninja的webui登录后，如果关闭了`Chat history & training`功能，不能连续进行对话，会提示`Conversation key not found. Try starting a new conversation.`。
这个是feature还是bug呢？

**Comment by gngpp** [comment]
关掉肯定不能连续，这个历史记录，一次性对话，自己带上下文

**Comment by nekomiya-hinata** [comment]
因为官方web页面上关了这个不影响连续对话，所以有点疑惑，谢谢回答

**Comment by Naist4869** [comment]
官网和潘多拉都不影响连续对话 这可能是ninja的bug
![image](https://github.com/gngpp/ninja/assets/37408934/9d8ec99b-f1e5-4d1f-9081-d440916eacff)
![image](https://github.com/gngpp/ninja/assets/37408934/9db7f9ce-abf7-4dba-a0a0-17a51b4f1548)

![image](https://github.com/gngpp/ninja/assets/37408934/ba492cf4-4c38-4351-b8ec-2db367657147)
