### ISSUE TITLE
invalid arkose token (No solver available)

### ISSUE THREAD

**Issue by yijia5478** [gngpp/ninja#310]
部署成功后，是直接使用官方账号在web ui界面登录就行吗？

使用docker 和docker compose 都能部署成功，但是上传har之后，使用官网账号无法登录

**Comment by gngpp** [comment]
日志呢？你上传什么类型HAR

**Comment by yijia5478** [comment]
我用的是 3.5 。 
尝试了使用har 和删除har 都不能使用官网账号登录。
使用的是 微软云的 机器。
debian 11
![image](https://img.52cn.me/i/2023/11/17/scp3do.png)
![image](https://img.52cn.me/i/2023/11/17/seizz0.png)

**Comment by gngpp** [comment]
你这什么玩意？怎么会是tcr9i接口

**Comment by yijia5478** [comment]
![image](https://img.52cn.me/i/2023/11/18/jxkgur.png)
这个地方写的啊，用tcr9i。就是直接复制readme里面的compose 配置
