### ISSUE TITLE
{"detail":{"message":"Client challenge required","code":"challenge_required"}} 

### ISSUE THREAD

**Issue by Dude998** [gngpp/ninja#315]
不知道什么错误好像说是什么灰度, 8.4后基本都这个提示
{"detail":{"message":"Client challenge required","code":"challenge_required"}}

**Comment by gngpp** [comment]
那你就退回去，你的IP出验证码了

**Comment by Dude998** [comment]
老大看看能不能直接对接一下验证码直接使用平台给识别了

**Comment by gngpp** [comment]
没精力，为什么要干这些吃力不讨好的事情？源码的都开源了也没有人PR

**Comment by caonuan** [comment]
有啥办法解决不大佬，我访问官网也是通过这个ip访问的，也没跳弹窗，但走ninja的就不行

**Comment by gngpp** [comment]
没救了，能解决早就解决了，直接换IP省事

**Comment by caonuan** [comment]
> 有啥办法解决不大佬，我访问官网也是通过这个ip访问的，也没跳验证码，但走ninja的就不行

突然又好了，可能拿这个ip走官网正常登录使用一下有帮助
