### ISSUE TITLE
 csrf token verify failed

### ISSUE THREAD

**Issue by zwbx** [gngpp/ninja#318]
![Screenshot 2023-11-18 at 18 30 41](https://github.com/gngpp/ninja/assets/38418735/2c697661-6eef-4352-9288-6b19c972a386)
This is really great work. However, I've encountered an error. Could it be due to an improper setting?

**Comment by gngpp** [comment]
You are using the login interface of WebUI. This interface has security precautions. You should use the `/auth/token` API to login.

**Comment by gngpp** [comment]
https://github.com/gngpp/ninja/blob/763e933e52b37472f5ec8004a6cd51f4fb0054f0/openai/src/serve/mod.rs#L274
