### ISSUE TITLE
手动运行报错，无法和openai建立ssl链接

### ISSUE THREAD

**Issue by RockyZ** [gngpp/ninja#322]
抓包对比，网页请求chat.openai.com域名没问题。通过ninjia请求的conversation backend_api怎么都不能建连。是啥原因？

![image](https://github.com/gngpp/ninja/assets/1710275/57b7c408-d446-4015-8b48-009d4940f045)
![image](https://github.com/gngpp/ninja/assets/1710275/2786d2e9-63f4-43d2-95ca-ddd81280b932)

**Comment by gngpp** [comment]
![Uploading image.png…]()
OpenAI跑路了

**Comment by gngpp** [comment]
环境变量是什么名称，all_proxy 这种才支持，要么--proxies

**Comment by RockyZ** [comment]
上面两种方式都是了，都不行。clash全局代理可以。

> 环境变量是什么名称，all_proxy / PROXIES 这种才支持，要么--proxies socks://xxx:8080 --disable-direct

**Comment by gngpp** [comment]
原来是clash，clash起的代理都有点问题

**Comment by gngpp** [comment]
<img width="1955" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/f8d3f798-9899-476a-9be2-e82491bb2a75">

**Comment by gngpp** [comment]
试了下是没啥问题的，clash的代理规则需要自己手动设置一下，要么直接就启用全局拦截
<img width="956" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/61be70a2-99b2-4c1d-af54-ab39a2aeb157">

<img width="1941" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/2be2888d-2d6d-4275-8db8-f731cf0b8b0c">
