### ISSUE TITLE
转 api 貌似出现问题

### ISSUE THREAD

**Issue by xiaokun19931126** [gngpp/ninja#326]
昨天应该还可以正常使用，今天早上转 api 接口报 401 token 过期，但是登录 chat 官网，token 并没有过期。于是更新 ninja 版本，重新 run 之后，转api 接口返回了一个 html ，类似下面这样：
2023/11/22 11:22:18.411 : onResponse json:<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="title" content="ChatGPT: Get instant answers, find inspiration, learn something new"><meta name="keywords" content="ai chat,ai,chap gpt,chat gbt,chat gpt 3,chat gpt login,chat gpt website,chat gpt,chat gtp,chat openai,chat,chatai,chatbot gpt,chatg,chatgpt login,chatgpt,gpt chat,open ai,openai chat,openai chatgpt,openai"><meta property="og:description" content="A conversational AI system that listens, learns, and challenges"><meta name="robots" content="index, follow"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta property="og:title" content="ChatGPT"><meta property="og:image" content="https://chat.openai.com/images/chatgpt-share-og.png"><meta property="og:url" content="https://chat.openai.com"><meta name="apple-itunes-app" content="app-id=6448311069"><title>404: This page could not be found</title>

请问这是官方服务器繁忙高负载导致的问题吗？

**Comment by gngpp** [comment]
接口路径跟官方一致了，改回官方的API路径

**Comment by xiaokun19931126** [comment]
<img width="765" alt="image" src="https://github.com/gngpp/ninja/assets/18168000/dc7633f2-21c3-48c9-a0be-0ee052238c50">
不明白为啥 用 java 程序发起的 请求报 body empty ，但是我看其实是发了 body的，之前的版本这么发没问题。

但是用 curl 来发又是正常的，好奇怪

<img width="617" alt="image" src="https://github.com/gngpp/ninja/assets/18168000/84733bc4-eec3-455e-af20-1aeb8fe70b1e">

**Comment by gngpp** [comment]
因为我强制了只接收这些content type，看你客户端有没有给你覆盖了
<img width="1103" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/3d72d4dc-8ca6-4a24-abc2-e6dfc6f457cb">

参考：https://github.com/gngpp/ninja/issues/325

**Comment by xiaokun19931126** [comment]
忘记回 fix 方案了，这个问题貌似是 okhttp 库的一个 “独特feature”，会默认添加  charset=utf-8。

<img width="898" alt="image" src="https://github.com/gngpp/ninja/assets/18168000/19862acf-4c62-48b8-aecd-6a992549ef69">

而且 okhttp 库开发者很执拗，就是不改，https://github.com/square/okhttp/issues/3081

workaround 方式：
1. 使用 byteArray 创建 RequestBody 
2. 使用 拦截器重新赋值 contentType

这个问题比较离谱的是，okhttp 默认添加 charset=utf-8 ，但是在 logger 拦截打印器中打印的 contentType 又不包含 charset=utf-8，最后还是 wireShark 抓包发现“蛛丝马迹”。
