### ISSUE TITLE
是否有计划支持GPTs以及GPTs的Chat2api

### ISSUE THREAD

**Issue by sebastian0619** [gngpp/ninja#348]
如题，GPTs最近尝试以后，可玩性都提高到了更高的层次。

如果能将GPTs的请求和对话再封装成Chat2API，可以更方便的搭配chatgpt-on-wechat等项目使用...

恳请考量，谢谢！

**Comment by gngpp** [comment]
我没有plus

**Comment by oreasono** [comment]
> 我没有plus

shared w/ you a PLUS account in email, enjoy!
