### ISSUE TITLE
关闭，走人

### ISSUE THREAD

**Issue by WangsYi** [gngpp/ninja#387]
不用你算命了

**Comment by WangsYi** [comment]
补充： 在容器中执行curl https://ifconfig.me可以正常访问

**Comment by gngpp** [comment]
然而你连一份debug日志都不愿意发？算命吗？，docker使用大多数人都没有你这个问题

**Comment by gebederry** [comment]
![4E2658F8-D94D-462B-9ACE-98A09060BA5E](https://github.com/gngpp/ninja/assets/3938353/884e7677-b592-4b44-8e3b-9e4750713427)
