### ISSUE TITLE
 /api/auth/session 接口在 0.9.5 不能正常返回数据

### ISSUE THREAD

**Issue by yv-code** [gngpp/ninja#389]
最近更新了 ninja 0.9.5 版本，发现之前刷新 AccessToken 的脚本出错了。

经过排查发现，ninja 的 `/api/auth/session` 依然返回 200 的 HTTP code，但内容是 404 的网页。

0.9.2 是最后一个可以正常通过 `/api/auth/session` 刷新 __Secure-next-auth.session-token 和 AccessToken 的版本。

**Comment by gngpp** [comment]
接口早就更新了，翻翻文档
