### ISSUE TITLE
打码失败

### ISSUE THREAD

**Issue by clcc2019** [gngpp/ninja#392]
yescaptcha一个账户消耗我几千积分，关键还登录失败

**Comment by gngpp** [comment]
登录经常抽风，没办法的事，你看看是不是返回303跳首页

**Comment by ludashi2020** [comment]
有没有办法让用户在前端手动打码呢？

**Comment by clcc2019** [comment]
> 登录经常抽风，没办法的事，你看看是不是返回303跳首页

这个能不能限制下打码平台失败次数？有个问题就是账户被封，但是登录时不会提示，一直调用打码平台导致消耗完额度

**Comment by gngpp** [comment]
你发个被封的账号给我，我修复一下提示

**Comment by gngpp** [comment]
邮箱gngppz@gmail.com

**Comment by gngpp** [comment]
登录目前，被封的账号有403提示，403就不要再继续登录了，其他是正常问题，数次登不上我建议隔一段时间再登。打码提交答案失败是会返回提示的，打对了，继续登还是会有概率失败，会跳到首页。这是无法避免，网页登也是一样，至少我是这样。
