### ISSUE TITLE
无法获取refresh token

### ISSUE THREAD

**Issue by cyx1322** [gngpp/ninja#402]
提示：2023-12-21T12:00:39.691980Z ERROR mitm::proxy::mitm: Tls accept failed: tls handshake eof

**Comment by gngpp** [comment]
信任证书了没

**Comment by cyx1322** [comment]
手机上信任了

**Comment by gngpp** [comment]
发更多的日志来，截图证书信任，这个就是证书没信任的日志

**Comment by cyx1322** [comment]
![IMG_7029](https://github.com/gngpp/ninja/assets/81369393/af51685a-6553-4a2b-a058-e6267035c144)
![IMG_7028](https://github.com/gngpp/ninja/assets/81369393/5cb9d78b-2d94-48ab-a31b-b52b600c3609)
![IMG_7027](https://github.com/gngpp/ninja/assets/81369393/74e9666f-e488-4f2a-b45b-ff0f7396c533)

**Comment by gngpp** [comment]
你这只是安装 不是信任，这个才是信任![image](https://github.com/gngpp/ninja/assets/51810656/8226c4a5-3e9e-4deb-a796-69d7d48f34f7)

**Comment by gngpp** [comment]
启动参数加上-L debug，随便打开个app一堆日志就是表示成功连上了

**Comment by cyx1322** [comment]
好的，谢谢大佬
