### ISSUE TITLE
希望chat to API中增加gpt-4-mobile模型支持

### ISSUE THREAD

**Issue by cyx1322** [gngpp/ninja#404]
如题。

**Comment by gngpp** [comment]
你想指定模型发，还是需要加什么后缀

**Comment by cyx1322** [comment]
是的，我想指定“gpt-4-mobile”发送。因为这个模型没有默认gpt4三小时40条的限制。
经测试，在ninja提供的backend api中可直接调用这个模型；但在chat2API中，即使指定model为“ gpt-4-mobile”，还是会使用默认的gpt4发送，有3小时40次的限制。

**Comment by cyx1322** [comment]
刚才试了一下，使用chat2api超过40条后还是会出现：
openai.RateLimitError: Error code: 429 - {'code': '429', 'msg': 'HTTP status client error (429 Too Many Requests) for url (https://chat.openai.com/backend-api/conversation)'}
但使用backend api就正常，猜测是因为chat-completion API会先验证账号是否还有常规gpt-4的次数剩余。但对于plus用户来说，即使40次已经用完，也可以正常使用gpt-4-mobile

**Comment by gngpp** [comment]
这还没编译完呢，你怎么就试了

**Comment by cyx1322** [comment]
刚才发的这个不是吗
![image](https://github.com/gngpp/ninja/assets/81369393/b455a438-0836-4e3c-8b52-58b4a1a1dc3d)

**Comment by gngpp** [comment]
都没编译完
![image](https://github.com/gngpp/ninja/assets/51810656/85cfba4e-dc9f-40d2-bed4-e81d061cdf04)

**Comment by gngpp** [comment]
你用macos？

**Comment by cyx1322** [comment]
好的好的，我再等等哈

**Comment by cyx1322** [comment]
我在Mac上先试试

**Comment by cyx1322** [comment]
确实可以了，谢谢大佬
