### ISSUE TITLE
有没有可能实现将dall-e-3接入到chat2api

### ISSUE THREAD

**Issue by mycurjerry** [gngpp/ninja#407]
大佬您好,目前这个项目的网页端可以用画图功能，但是chat2api好像不能显示图片（已附图）
不知道chat2api有没有可能实现增加一个类似显示dall-e-3画图的URL的功能.
比如api返回
```
https://files.oaiusercontent.com/file-xxx
这是一幅栩栩如生的猫咪画作。
```
如果可行的话，您会考虑在今后的版本增加这个功能吗，感谢。
<img width="516" height="700" alt="image" src="https://github.com/gngpp/ninja/assets/143496597/05d718ad-c6a1-47e3-97c9-f34972bef87d">
<img width="889" alt="image" src="https://github.com/gngpp/ninja/assets/143496597/33adcb03-56d5-49ca-be5f-8b387e14b8c6">
stat已点亮

**Comment by gngpp** [comment]
可能的，欢迎有人来PR
