### ISSUE TITLE
v0.9.7 /auth/refresh_session 接口调用返回 Json deserialize error

### ISSUE THREAD

**Issue by yv-code** [gngpp/ninja#413]
上次没有仔细看 doc  ，这次出问题去看文档，发现接口变成了 POST 方法，传参也统一使用了 `Authorization: Bearer xxxx`。

结合这个 722eb2c commit，我将 `__Secure-next-auth.session-token` cookie 的 value，以 `Authorization` header 的形式传入，依然返回 400 错误，Response body 如下：

```
{
  "code": "400",
  "msg": "Json deserialize error (error reqwest::Error { kind: Decode, source: Error(\"missing field `user`\", line: 1, column: 2) })"
}
```
期间我使用新登录获取的 `__Secure-next-auth.session-token` 依旧是一样的错误，而在老版本 (v0.9.5) 上使用是正常的，所以应该能排除 session-token 本身的问题。

尝试查看源码，无奈不会 Rust，所以提交 Issue。不太确定是 BUG 还是我用法不对。

**Comment by gngpp** [comment]
没问题啊，你的可能是失效了，发你的session到我邮箱我来试试，顺便修复一下错误提示：gngppz@gmail.com
<img width="1234" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/3d00bccc-8455-4e66-b910-9c928b48b1ef">

**Comment by yv-code** [comment]
是我这边的问题，又尝试了一下，可以了。
不过错误提示的确有点让人摸不着头脑

**Comment by gngpp** [comment]
应该是官方接口出问题了，有时候会返回{}，然后就序列化出问题了

**Comment by yv-code** [comment]
感谢解答

> 应该是官方接口出问题了，有时候会返回{}，然后就序列化出问题了
