### ISSUE TITLE
是否有选项可以不使用内置DNS

### ISSUE THREAD

**Issue by AlliotTech** [gngpp/ninja#417]
Hi, ninja在某个版本之后内置了DNS，这会导致外部的分流规则无法使用域名来做， 这里是否有一个选项可以将解析交给Proxy呢？

**Comment by gngpp** [comment]
有proxy，解析默认是给代理啊
有代理：
<img width="1535" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/893664ba-bd33-4471-a982-bc7bab617af3">

无代理：
<img width="1513" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/0bc28ef8-babc-4f23-a90a-b8281f539310">

**Comment by gngpp** [comment]
内置的DNS查询协议只使用了`TCP`/`UDP`

**Comment by AlliotTech** [comment]
上游proxy使用域名来进行分流，因此给openai相关的域名指定了节点，似乎在某个版本后，在proxy的日志里看到的不再是domain而是IP了，域名规则就失效了。

**Comment by gngpp** [comment]
你是说像这种么
<img width="1277" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/85943051-7fc2-465c-ab17-1904204f12be">

**Comment by AlliotTech** [comment]
预期的行为: 
ninja发起向openai的请求，通过proxy，proxy根据域名做分流，解析IP。

实际行为:
ninja发起向openai的请求，传到proxy的是`TCP` `UDP`，proxy拿到的是IP，只能通过GEOip来分流: 
<img width="1402" alt="image" src="https://github.com/gngpp/ninja/assets/24980252/267aafc3-9147-4cea-b7c4-59349e576c6b">

**Comment by gngpp** [comment]
实际上走代理，内置的dns根本没有参与解析。而是交给了代理，你得用socks5h协议
<img width="1781" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/9189ca5a-567c-4f8a-92ab-964a7f3e732f">

**Comment by gngpp** [comment]
socks5h协议让DNS解析交给了代理去解析

**Comment by AlliotTech** [comment]
Great catch!   确实， 测试后发现问题在socks5h。  目前用的socks5。

**Comment by AlliotTech** [comment]
https://superuser.com/questions/1762341/does-chromium-not-support-socks5h-with-the-h-in-the-end/1762355#1762355
