### ISSUE TITLE
文档 doc/python-requests.ipynb 中参数顺序错误

### ISSUE THREAD

**Issue by QvQQ** [gngpp/ninja#422]
1. 文档中的参数是这样定义的，先`current_message_id`，再`parent_message_id`。
<img width="775" alt="image" src="https://github.com/gngpp/ninja/assets/35735975/157f561f-ba1b-44e7-a770-d1bb3bbba2f1">

2. 文档紧接着的示例里是这样写的，先`parent_message_id`，再`current_message_id`。
<img width="975" alt="image" src="https://github.com/gngpp/ninja/assets/35735975/b5829b55-c582-47c0-9828-1f7fdd66a372">

3. 结果会造成所有`role`为`user`的`message`合并到一起，但只保留最后一条`assistant`的回复。

- 期望结果：
<img width="813" alt="image" src="https://github.com/gngpp/ninja/assets/35735975/e6811e1a-c595-4c6d-b1a8-071101a1852a">

- 该示例结果：
<img width="617" alt="image" src="https://github.com/gngpp/ninja/assets/35735975/fe64b54b-1c01-4f80-81ba-84b230ac7265">

**Comment by gngpp** [comment]
来pr修复，这个文档不是我写的
