### ISSUE TITLE
fix tcp keepalive

### ISSUE THREAD

**Issue by Naist4869** [gngpp/ninja#423]
官网和潘多拉都不影响连续对话 这可能是ninja的bug
![image](https://github.com/gngpp/ninja/assets/37408934/9d8ec99b-f1e5-4d1f-9081-d440916eacff)
![image](https://github.com/gngpp/ninja/assets/37408934/9db7f9ce-abf7-4dba-a0a0-17a51b4f1548)

![image](https://github.com/gngpp/ninja/assets/37408934/ba492cf4-4c38-4351-b8ec-2db367657147)

_Originally posted by @Naist4869 in https://github.com/gngpp/ninja/issues/307#issuecomment-1879605898_

**Comment by gngpp** [comment]
老UI的问题，不是bug，没有计划更新

**Comment by ysben** [comment]
邮箱密码登录这个有打算更新吗？我看现在都一直出错，我提交issues一直被屏蔽

**Comment by QvQQ** [comment]
> 邮箱密码登录这个有打算更新吗？我看现在都一直出错，我提交issues一直被屏蔽

邮箱密码登录怎么了吗

**Comment by ysben** [comment]
> > 邮箱密码登录这个有打算更新吗？我看现在都一直出错，我提交issues一直被屏蔽
> 
> 邮箱密码登录怎么了吗

你没用过吗？一直提示自动返回首页

**Comment by gngpp** [comment]
你IP/arkose有问题，我很少遇到跳首页的

**Comment by gngpp** [comment]
登录就那个流程，没有什么好更新的

**Comment by ysben** [comment]
arkose就是接口下载的那个文件吗？

**Comment by QvQQ** [comment]
@gngpp 我发现如果用的代理是轮换动态代理（每次发起请求都会改变代理地址）的话，ninja似乎会重用连接，导致仍然会在同一代理IP下连续请求。
例如……当我连续对多个账号使用账号密码请求`/auth/token`获取`session_token`时，每7~10次就会报`Failed Login`，只有重启ninja才会解决问题。
（`pool_idel_timeout`设置为1或0、`no_keep_alive`=true）都没用诶，我的程序内捕获异常后延时重试也没有用。

这个问题要怎么解决嘞？

**Comment by ysben** [comment]
> @QvQQ 你是用邮箱和密码获取session_token？怎么做的？请教一下

**Comment by gngpp** [comment]
> @gngpp 我发现如果用的代理是轮换动态代理（每次发起请求都会改变代理地址）的话，ninja似乎会重用连接，导致仍然会在同一代理IP下连续请求。 例如……当我连续对多个账号使用账号密码请求`/auth/token`获取`session_token`时，每7~10次就会报`Failed Login`，只有重启ninja才会解决问题。 （`pool_idel_timeout`设置为1或0、`no_keep_alive`=true）都没用诶，我的程序内捕获异常后延时重试也没有用。
> 
> 这个问题要怎么解决嘞？

<img width="636" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/273ac1cb-f8fa-4681-9b04-ecae98a42bbd">
谁的问题？

**Comment by gngpp** [comment]
登录次数过多可能也会429，我没有处理，自然就failed login
<img width="1206" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/d7af6009-087c-41f3-93b3-85eeafb00c8e">

**Comment by gngpp** [comment]
每个请求client都会独立绑定一个唯一代理，一次登录上下文始终使用一个客户端，没有毛病

**Comment by ysben** [comment]
@gngpp 有推荐的代理池吗？

**Comment by ysben** [comment]
> 没有，可以去买一台带ipv6 /48子网vps

在这vps里面搭建还是要用到地理IP吧，不然账号多了会被限制？

**Comment by gngpp** [comment]
单IP是有限制的，自己用无所谓

**Comment by QvQQ** [comment]
> > @QvQQ 你是用邮箱和密码获取session_token？怎么做的？请教一下
请求的是`/auth/token`这个接口，你可以改改

```python
@retry(tries=2, delay=20, backoff=1, exceptions=(requests.exceptions.HTTPError, requests.exceptions.ConnectionError))
def get_access_and_session_token_ninja(email, password):
    log.info('Fetching [bold white]access token[/bold white] and [bold white]session token[/bold white]...')

    url = "http://localhost:7999/auth/token"

    headers = {
        'Content-Type': 'application/x-www-form-urlencoded'
    }

    data = {
        'username': email,
        'password': password
    }

    try:
        res = requests.post(url, headers=headers, data=data, verify=False)
        res.raise_for_status()
    except requests.exceptions.HTTPError as http_err:
        log.error(f'HTTP Error. content: {http_err.response.text}')
        log.error(f'`ninja` restarting...')
        subprocess.run(f'sudo ./ninja restart -C serve.toml', shell=True)
        raise
    except requests.exceptions.ConnectionError as con_err:
        raise

    json_content = res.json()
    if (
        (session_token := json_content.get('session_token')) and
        (access_token := json_content.get('accessToken')) and
        len(session_token) > 0 and
        len(access_token) > 0  # noqa
    ):
        log.info('Got it.')
        return session_token, access_token
    else:
        log.error(f'Fetch failed. json_content:')
        log.error(json_content)

    return None, None
```

**Comment by ysben** [comment]
@QvQQ  代理怎么配置呢?

**Comment by QvQQ** [comment]
> @QvQQ 代理怎么配置呢?

@ysben 代理是ninja这里配置的呀

**Comment by ysben** [comment]
@QvQQ 我是docker部署的，总觉得配置的代理不对，一直都是获取不到accesstoken

**Comment by ysben** [comment]
@QvQQ  大佬，你有遇到这情况吗？
{
    "code": "400",
    "msg": "Accidentally jumped back to the login homepage, please try again."
}

**Comment by QvQQ** [comment]
> @QvQQ 大佬，你有遇到这情况吗？ { "code": "400", "msg": "Accidentally jumped back to the login homepage, please try again." }

这个可能也是因为IP不干净，加异常多重试多换IP

**Comment by ysben** [comment]
@QvQQ 你是怎么操作的呢？我用的住宅IP动态换的，不知道方式对不对,我docker配置是这样
TZ=Asia/Shanghai
proxies=socks5h://账号:密码@IP:端口
arkose-solver-key=xxxxxxx
arkose-solver=yescaptcha
enable-direct=true

**Comment by QvQQ** [comment]
@ysben 我没用docker，但没什么问题看起来这样？如果只是偶发这个报错的话，可以直接忽略

**Comment by ysben** [comment]
@QvQQ 是不是要用asocks的代理才行？

**Comment by zhuxindong** [comment]
> > @gngpp 我发现如果用的代理是轮换动态代理（每次发起请求都会改变代理地址）的话，ninja似乎会重用连接，导致仍然会在同一代理IP下连续请求。 例如……当我连续对多个账号使用账号密码请求`/auth/token`获取`session_token`时，每7~10次就会报`Failed Login`，只有重启ninja才会解决问题。 （`pool_idel_timeout`设置为1或0、`no_keep_alive`=true）都没用诶，我的程序内捕获异常后延时重试也没有用。
> > 这个问题要怎么解决嘞？
> 
> <img alt="image" width="636" src="https://private-user-images.githubusercontent.com/51810656/294838285-273ac1cb-f8fa-4681-9b04-ecae98a42bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzc1MTQsIm5iZiI6MTcwNDg3NzIxNCwicGF0aCI6Ii81MTgxMDY1Ni8yOTQ4MzgyODUtMjczYWMxY2ItZjhmYS00NjgxLTliMDQtZWNhZTk4YTQyYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA5MDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MDc4ZjU1Mzc3MDBjODk2ZTk3MjgwNWJjYzNhMTAxMGVlMzIxYzE1MzJmMTYwZmEwNmQwZmI2MzYzNmFjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IGJ7p0fGjQRuL-K2cA2VJdAXL_wkzlcTWEui50N9xDI"> 谁的问题？

curl每次都会新建连接，而ninja会和openai之间有http的keepalive属性，所以一直不会换新的ip

**Comment by gngpp** [comment]
发现毛病了，上游的问题
<img width="1204" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/873e5f6f-28c9-4a62-a614-9056834da12c">

**Comment by zhuxindong** [comment]
是reqwest这个库的keepalive设置是无效的是吧

**Comment by gngpp** [comment]
目前发现只针对使用代理没有生效，重新创建客户端不会复用链接
