### ISSUE TITLE
sess token获取不到

### ISSUE THREAD

**Issue by clcc2019** [gngpp/ninja#424]
POST /auth/sess_token
支持获取sess吗

**Comment by gngpp** [comment]
需要带platform的access token才能获取（而不是chatgpt）

**Comment by gngpp** [comment]
补充：
<img width="1146" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/15648bf6-0df8-4d21-a832-785f4e6d6259">

**Comment by clcc2019** [comment]
> 补充： <img alt="image" width="1146" src="https://private-user-images.githubusercontent.com/51810656/295099640-15648bf6-0df8-4d21-a832-785f4e6d6259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODEwMDksIm5iZiI6MTcwNDc4MDcwOSwicGF0aCI6Ii81MTgxMDY1Ni8yOTUwOTk2NDAtMTU2NDhiZjYtMGRmOC00ZDIxLWE4MzItNzg1ZjRlNmQ2MjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA2MTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NDFlNGNiYjQyODViZWYwYzE3MmZiZDk5OWZhYWY3ZThiYmU4ZDBmNjA4ZmJmNmI5Yzg4MWE5OTg2NTYxODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pYAUsRkktK4irjm9w3yCW4N9qZ3SDUJEgnt1arBrN4g">

thanks，可以获取，token没对应

**Comment by QvQQ** [comment]
@clcc2019 请问一下platform的access token从哪个接口获取呀？
是请求`http://localhost:7999/dashboard/onboarding/login`获取吗？
我看接口文档如果请求`/dashboard/onboarding/login`需要带上`Bearer {{access_token}}`，但这样不就套娃了[捂脸]
提示这样：
```json
{
    "error": {
        "message": "The application you are using is not allowed to call this endpoint. If error persists, contact us through our help center at help.openai.com and include the following request ID: 2fca05f75a6e4878c66789d078144ee2.",
        "type": "invalid_request_error",
        "param": null,
        "code": "unsupported_client"
    }
}
```
