### ISSUE TITLE
team版本出来了，有打算做team的适配吗？

### ISSUE THREAD

**Issue by weikecloud** [gngpp/ninja#435]

**Comment by heurainbow** [comment]
@gngpp  team的成员采用原来获取token和har文件的方式部署会报500错误 可以解决么

**Comment by gngpp** [comment]
发日志来

**Comment by heurainbow** [comment]
升级到最新版ninja重新隔离部署测试了一下。发现是The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4. 
应该是team成员（无gpt4的权限）在加入teamspace后有一层认证或者转发到其他的位置，而不像直接在个人账户中对话。

**Comment by gngpp** [comment]
你去官网抓包看看怎么验证就知道了

**Comment by heurainbow** [comment]
不会看前端呀，大佬能不能搞一下适配team的模式，我可以提供个成员账户供实验 @gngpp

**Comment by gngpp** [comment]
有空先，我现在还没空更新UI

**Comment by yongman** [comment]
@heurainbow 等周末我研究一下，留个联系方式，到时候是否可以借用一下 team 账号调试一下？aHR0cHM6Ly90Lm1lL3lvbmdtYW4=

**Comment by heurainbow** [comment]
> @heurainbow 等周末我研究一下，留个联系方式，到时候是否可以借用一下 team 账号调试一下？aHR0cHM6Ly90Lm1lL3lvbmdtYW4=

已发到你的github主页邮箱

**Comment by liaosunny123** [comment]
>  @gngpp  team的成员采用原来获取token和har文件的方式部署会报500错误 可以解决么

请问这个team指的是哪一个？
1. 加入Team且使用workspace的账号（100条/3h）
2. 加入Team且使用个人账号（无plus充值，40条/3h，无gpts）
第二个我测试过了好像是可以用的。

但是我不清楚如何在ninja里面区分这两个不同的账号模式

**Comment by yongman** [comment]
@heurainbow @liaosunny123 目前 ninja API 已经支持了区分 team 账号，需要在请求中带上 header `Chatgpt-Account-Id: xxx`。

**Comment by weikecloud** [comment]
@yongman Chatgpt-Account-Id: 在哪可以获得呢？

**Comment by yongman** [comment]
@weikecloud The team account id can be acquired from `https://chat.openai.com/backend-api/accounts/check/v4-2023-04-27`.

**Comment by weikecloud** [comment]
@yongman 我需要更新ninja吗？

**Comment by liaosunny123** [comment]
> @heurainbow @liaosunny123 目前 ninja API 已经支持了区分 team 账号，需要在请求中带上 header `Chatgpt-Account-Id: xxx`。

100h/3h的需要携带Chatgpt-Account-Id: xxx
40/3h的(加入team的无plus账号)直接按照以前的方式操作，是这个意思嘛

**Comment by xiaosaaaa** [comment]
> @weikecloud The team account id can be acquired from `https://chat.openai.com/backend-api/accounts/check/v4-2023-04-27`.

能否在启动参数里直接加上Chatgpt-Account-Id：xxx来区分团队版和个人版，加了参数走团队版，不加就按原来的走个人版，这样在第三方客户端里就能调用团队版的账号了。

**Comment by yongman** [comment]
> 那能否在启动参数里直接加上Chatgpt-Account-Id：xxx来区分团队版和个人版，加了参数走团队版，不加就按原来的走个人版，这样在第三方客户端里就能调用团队版的账号了。

team 账号下 personal account 和 team account 都有 gpt4 额度，通过判断请求 header 里是否有 account-id 会更加灵活，可以按需选择使用，也可以增加一些调度逻辑，达到 gpt4 的充分利用。单个 ninja 实例就可以同时支持两种账号。

**Comment by xiaosaaaa** [comment]
我如果在第三方客户端使用，如何加上account-id 来调用team版呢？

**Comment by yongman** [comment]
如果你不想改客户端代码，简单的方式是前面挂个 nginx 代理，增加一个 proxy_set_header 配置就可以了。

**Comment by gngpp** [comment]
In progress: https://github.com/gngpp/ninja/actions/runs/7754567580, has been updated to the latest UI
