### ISSUE TITLE
登录打码又不行了

### ISSUE THREAD

**Issue by clcc2019** [gngpp/ninja#436]
<img width="1265" alt="image" src="https://github.com/gngpp/ninja/assets/46099295/ef762639-3da1-49d8-8988-afb23e3ca9be">

**Comment by clcc2019** [comment]
Funcaptcha images count >= 5, your features are already in high risk control status

**Comment by nekomiya-hinata** [comment]
这个可能是ip太脏了导致的吧，打码数太多了

**Comment by gngpp** [comment]
什么时候开始的

**Comment by gngpp** [comment]
看一般用户都没有大量bda，arkose多了容易出码（前提是你有大量代理/IP），我打算弄个收集bda端点进去，可选开启。如果你们有大流量的任何网站可以集成到上面去收集。不知你们一下如何，🥵小心被用户骂😅，现在有的镜像站肯定有不少人这样干了🥱。取决于你们用不用

**Comment by clcc2019** [comment]
> 什么时候开始的

今天开始的，换了ip也不行，自己浏览器用同样的代理ip登录也就3个图

**Comment by gngpp** [comment]
你试一下用自带的UI网页登录试试能不能进去

**Comment by clcc2019** [comment]
> 你试一下用自带的UI网页登录试试能不能进去

一直转圈加载中

**Comment by clcc2019** [comment]
<img width="1067" alt="image" src="https://github.com/gngpp/ninja/assets/46099295/f61c6910-3f0d-40b3-b1fc-f5856953cd22">
<img width="1470" alt="image" src="https://github.com/gngpp/ninja/assets/46099295/9baf5863-c921-4d4e-938b-a39e90caaab8">
又挂了

**Comment by gngpp** [comment]
已经修好了，晚点更新

**Comment by gngpp** [comment]
你这不钓鱼么？怎么还出图

**Comment by clcc2019** [comment]
打不了码

**Comment by clcc2019** [comment]
老板，登录又挂了

**Comment by gngpp** [comment]
日志呢，能不能每次问**先上日志**，每次都靠猜。我刚才网页登陆还好好的
