### ISSUE TITLE
使用/v1/chat/completions返回网络错误418响应

### ISSUE THREAD

**Issue by brianler** [gngpp/ninja#437]
具体响应如下：
{"code":418,"msg":"HTTP status client error (418 I'm a teapot) for url (https://chat.openai.com/backend-api/conversation)"}

这种情形是什么原因？有时重启容器似乎能解决这个问题，但有时也不行

**Comment by gngpp** [comment]
被认成机器人了，自己换ua/ip，一直发conversation就会这样
