### ISSUE TITLE
关于 HAR 特征池化的询问

### ISSUE THREAD

**Issue by liaosunny123** [gngpp/ninja#439]
根据 API 描述可以实现多号使用同一个 ninja 实例，通过客户端保存不同的 AccessToken，Session等即可。但是文档中似乎没有说明发送某个消息可以直接指定某个 Har。
请问 Har 需要保证和账号相关联吗？如果需要的话，怎么可以使用多账户使用一个ninja实例？

**Comment by gngpp** [comment]
不需要，其实要的就是har文件里边的bda，bda你可以认为是一个浏览器指纹特征。
