### ISSUE TITLE
更换了多个ip 还是一直报 Accidentally jumped back to the login homepage, please try again.

### ISSUE THREAD

**Issue by ynpl** [gngpp/ninja#441]
更换了多个ip还是一直报
Accidentally jumped back to the login homepage, please try again.

**Comment by ynpl** [comment]
使用 access token 可以用, 账号密码登录不行

**Comment by weikecloud** [comment]
你需要配置har ，你去openai官方那边登录获取一下har文件然后上传到后台就行，我之前也是一直这样，后来解决了

**Comment by gngpp** [comment]
https://github.com/gngpp/ninja/releases/tag/v0.9.11

**Comment by weikecloud** [comment]
@gngpp 可以直接拉取镜像更新吗？

**Comment by gngpp** [comment]
这次恢复兼容以前的har
