### ISSUE TITLE
Web UI cannot be opened,

### ISSUE THREAD

**Issue by LiangNiang** [gngpp/ninja#443]
Web UI cannot be opened, the interface is blank, it seems that a JavaScript resource cannot be obtained from https://cdn.oaistatic.com/_next/static/chunks/webpack-f0d5d0ecb8743987.js
![image](https://github.com/gngpp/ninja/assets/20347803/bae2a6ec-4571-4a9d-bb9a-dd8f1392af1c)

**Comment by ChitoneDevOps** [comment]
Same question.
