### ISSUE TITLE
I don't understand why this is needed and how it is actually used

### ISSUE THREAD

**Issue by testinghere57564** [gngpp/ninja#444]
I was looking for cloudflare bypass and came across this thread. At first I thought that we were connecting to a chatgpt proxy that was on the white list and was not blocked. When I opened the documentation, I saw a bunch of stuffiness. As I understand it, authorization is described in an undocumented way, then an open API is published...

**Comment by gngpp** [comment]
If you don’t understand it, please don’t use it. This project is not for beginners who don’t know how to reverse engineer ChatGPT.

**Comment by testinghere57564** [comment]
> If you don’t understand it, please don’t use it.

So I understand correctly that we connect to the chatgpt proxy, then we bind it locally. And this IP is on the cloudflare whitelist and we won’t get 403?

**Comment by gngpp** [comment]
Ordinary HTTP request clients will block your connection directly after the TLS handshake and return 403.  You might as well try it yourself
