### ISSUE TITLE
Funcaptcha solver

### ISSUE THREAD

**Issue by gngpp** [gngpp/ninja#446]
会自己处理`arkoselabs funcaptcha`图像处理打码的可以试试项目：https://github.com/gngpp/fcsrv

如果没问题直接接入ninja。

只支持以下模型。
- `3d_rollball_animals`
- `3d_rollball_objects`
- `coordinatesmatch`
- `hopscotch_highsec`
- `train_coordinates`
- `penguin`
- `shadows`

**Comment by sm3xegg** [comment]
Hello how can I connect ninja to this solver as a docker container? Thanks in advance

**Comment by gngpp** [comment]
Not yet accessed for use
