### ISSUE TITLE
4.0提问出现问题

### ISSUE THREAD

**Issue by sopoka1999** [gngpp/ninja#447]
![13151705898073_ pic](https://github.com/gngpp/ninja/assets/30564011/5fbb70a9-c2cf-4250-ad47-d0377de528a1)

**Comment by gngpp** [comment]
废了

**Comment by gngpp** [comment]
这个问题频发的举个抓。推测是网络慢，arkose等待时间过期了

**Comment by sopoka1999** [comment]
我发现更换一个HAR文件就好了
