### ISSUE TITLE
登录以后出现 ChatGPT can make mistakes. Consider checking important information.

### ISSUE THREAD

**Issue by wwlmm** [gngpp/ninja#448]
查看 发现 webpack-f0d5.......js 404错误。
不知怎么解决。希望作者帮忙解决，谢谢！以下是登录以后的样子，没有界面，环境已经处于梯子下了。
![image](https://github.com/gngpp/ninja/assets/23204809/747e7207-0cca-4f91-b66f-6b5156125efe)

**Comment by gngpp** [comment]
cdn丢js了，看看有没有人愿意pr修复

**Comment by wwlmm** [comment]
> cdn丢js了，看看有没有人愿意pr修复

这应该不是我部署的问题是吗？

**Comment by yanchenglin** [comment]
webpack-f0d5d0ecb8743987.js 暫存檔案供參考.

[webpack-f0d5d0ecb8743987.js.gz](https://github.com/gngpp/ninja/files/14011927/webpack-f0d5d0ecb8743987.js.gz)

**Comment by Niansuh** [comment]
https://github.com/cockroachai/cdn-oaistatic

**Comment by gngpp** [comment]
想用新UI的，有条件可以自己去自建UI：https://github.com/xyhelper/chatgpt-mirror-server，openai接口可以改走你的网关或者他们的，自己随意。如果有人能把静态资源跟路由移植过来就更好了。

**Comment by zc16607** [comment]
> cdn丢js了，看看有没有人愿意pr修复

这个js是openai官方的文件吧，怎么会丢失。我的意思是丢失的话openai官网不是也登录不上去了吗。你给的解决办法有点看不懂，能详细说一下吗

**Comment by gngpp** [comment]
> > cdn丢js了，看看有没有人愿意pr修复
> 
> 这个js是openai官方的文件吧，怎么会丢失。我的意思是丢失的话openai官网不是也登录不上去了吗。你给的解决办法有点看不懂，能详细说一下吗

openai的cdn 资源丢了，你没看见上面404？官网的是新UI不一样

**Comment by jsxupeng** [comment]
> 想用新UI的，有条件可以自己去自建UI：https://github.com/xyhelper/chatgpt-mirror-server openai接口可以改走你的网关或者他们的，自己随意。如果有人能把静态资源跟路由移植过来就更好了。



> cdn丢js了，看看有没有人愿意pr修复

请求里的cdn这个网址在本项目哪个文件里改？

**Comment by jsxupeng** [comment]
> 请求里的cdn这个网址在本项目哪个文件里改？

请求里的cdn这个网址在本项目哪个文件里改？
