### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by wkpgzz** [gngpp/ninja#458]
使用容器和二进制文件直接部署服务后，登入账号后页面会报错Application error: a client-side exception has occurred (see the browser console for more information).
F12看到有https://chatgpt.com/status接口CORS ERROR

**Comment by gngpp** [comment]
有些号进不去的 UI比较老，只推荐用普号

**Comment by wkpgzz** [comment]
> 有些号进不去的 UI比较老，只推荐用普号

这个和opneai的账号有关？我用的就普通的账号

**Comment by gngpp** [comment]
因为有些号 多了些账号属性 老UI它不认 就崩溃了，我有几个小号，有个别是这样的

**Comment by gngpp** [comment]
有一个发现是，如果之前加入过team的号，没有主动退出，在老UI就会崩溃

**Comment by wkpgzz** [comment]
> 有一个发现是，如果之前加入过team的号，没有主动退出，在老UI就会崩溃

主动退出team后，还是一样的报错

**Comment by gngpp** [comment]
没救 换号

**Comment by gngpp** [comment]
In progress: https://github.com/gngpp/ninja/actions/runs/7754567580, has been updated to the latest UI
