### ISSUE TITLE
很快会出现提问和回答相同的情况

### ISSUE THREAD

**Issue by heurainbow** [gngpp/ninja#459]
更新到0.9.13后，会很快出现问什么答什么的现象。更新har文件后会短暂的正常，但访问几次后就又出现该情况。

问题是tell a short joke，回答是
{
  "content": "tell a short joke",
  "role": "assistant"
}

这个情况下去页面端会出现验证环节
![image](https://github.com/gngpp/ninja/assets/6753276/470f145a-0b52-441d-90f8-61e75a9aea26)

**Comment by gngpp** [comment]
这个情况不知道 感觉是被openai识别了

**Comment by heurainbow** [comment]
连续运行好久了，最近发现的问题。是不是跟我每次请求都是单独调用的create对话有关系。

**Comment by gngpp** [comment]
你是无聊到一直问同个问题？有时候他拒绝工作也是有可能

**Comment by heurainbow** [comment]
不是一直问一个问题，就是一直在搞SFT的对话数据。格式的相似程度比较高。

**Comment by gngpp** [comment]
这个我管不着，因为我只管转发，openai生成什么 跟我没有什么关系，既然它都回答了，重复答案不是不可能

**Comment by heurainbow** [comment]
用的就是http://ip:port/v1

**Comment by gngpp** [comment]
这个帖子就留在这里，看看其他人有没有什么看法。我虽然逆这个 但是几乎都不用。

**Comment by heurainbow** [comment]
猜测出问题的地方 
1 vps的IP 
2 代理的IP
3 对话行为审核
4 ninja有什么行为触发了审查
后续我会逐一尝试排查一下

**Comment by heurainbow** [comment]
arkose token is invalid, but no solver is available. @gngpp 这个是什么问题呀

**Comment by gngpp** [comment]
字面意思

**Comment by heurainbow** [comment]
明确问题就是被openai盯上了，和IP、内容、账户都有关系，账户在同样IP多次访问相近的内容就会触发。配置solver可以部分解决。主要还是要请求端和代理池解决。

**Comment by heurainbow** [comment]
我是不是应该参考https://github.com/gngpp/ninja/blob/main/doc/python-requests.ipynb 用后端的对话方式进行请求

**Comment by gngpp** [comment]
对，转API的格式我不确定是不是更新了，所以是有可能被认出来了

**Comment by heurainbow** [comment]
@gngpp 大佬说的对，用backend-api请求是没问题的，也不需要arkose solver了。
