### ISSUE TITLE
请问会支持gpt-4-mobile吗

### ISSUE THREAD

**Issue by assassinliujie** [gngpp/ninja#460]
做代码review的时候经常触碰到限额，请问这个不限额的gpt-4mobile可以方便对接一下吗

**Comment by gngpp** [comment]
很早就适配了 直接传模型就行了

**Comment by gngpp** [comment]
网页没有，要改接口，很麻烦

**Comment by t2ui** [comment]
网页其实可以用https://greasyfork.org/zh-CN/scripts/467244，加一条match就行
