### ISSUE TITLE
用python执行登录操作，返回{"code":"500","msg":"invalid Location"}

### ISSUE THREAD

**Issue by GitHubChrisChen8035** [gngpp/ninja#461]
‘‘’
import requests

url = "http://localhost:7999/auth/token"

payload = 'username=我的账号邮箱&password=登录密码&option=web'
headers = {
  'Content-Type': 'application/x-www-form-urlencoded'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
‘’‘

改了账号密码，其他地方没动，然后是用docker-compose方式启动的ninja项目。

![image](https://github.com/gngpp/ninja/assets/25357844/effb2a2b-8c06-415e-ae9b-eeda3dc05c7f)
![image](https://github.com/gngpp/ninja/assets/25357844/b0ff0146-d074-4809-ae2f-a9257ed27cb3)

**Comment by zzhhxx** [comment]
你的节点不太对劲

**Comment by gngpp** [comment]
你的节点不太对劲

**Comment by gngpp** [comment]
这种小问题就不要重复提问了，基本都是Arkose/IP问题

**Comment by GitHubChrisChen8035** [comment]
有没有支持mac系统的，好像目前看没有哎

**Comment by GitHubChrisChen8035** [comment]
> 这种小问题就不要重复提问了，基本都是Arkose/IP问题

节点应该没有问题的
![image](https://github.com/gngpp/ninja/assets/25357844/4981def2-94a1-4ffd-a95b-939da58ead07)
是不是因为我用的docker，而不是常规的可执行文件？？
