### ISSUE TITLE
fcsrv配置后无法获取arkose token

### ISSUE THREAD

**Issue by Payne-Wang** [gngpp/ninja#466]
大佬，根据昨天更新的内容在本地挂上fcsrv后，ninja环境变量中也加进去了

![image](https://github.com/gngpp/ninja/assets/44337721/86ae2b09-eba2-482b-b62d-b36365f7f3e8)

在请求gpt4后，返回内容为空，同时fcsrv没有日志输出（如下图），请问是我配置有问题嘛？感谢

![image](https://github.com/gngpp/ninja/assets/44337721/b57aef51-7b1f-4792-b9bf-c2d37b99b7e9)

**Comment by gngpp** [comment]
我还没发版呢，没有编译发布

**Comment by Payne-Wang** [comment]
好的，另外我试了YesCaptcha，对ninja的环境变量做了如下配置，也是不能用

![6459f58548851d24b02ed09c7cff278](https://github.com/gngpp/ninja/assets/44337721/c685ed79-ae89-4838-8c44-262c847f04b2)

**Comment by Payne-Wang** [comment]
完整环境变量配置如下：

![image](https://github.com/gngpp/ninja/assets/44337721/d75a5330-7101-41df-b3e2-cf8b011ba95f)

配置后访问gpt-4, 报错：
![image](https://github.com/gngpp/ninja/assets/44337721/ffd9263f-382c-4dc7-8c53-5cbfa00926a3)

同时YesCaptcha账户没有扣费

**Comment by gngpp** [comment]
不是什么环境变量都生效的，自己看看命令手册

**Comment by Payne-Wang** [comment]
> 不是什么环境变量都生效的，自己看看命令手册

哦哦！我明白了，谢谢

**Comment by gngpp** [comment]
对话码不是很容易过么，怎么你这还出码了

**Comment by Payne-Wang** [comment]
> 对话码不是很容易过么，怎么你这还出码了

arkose solver的配置不是在环境变量，而是在命令行里面设置吧。我设置成环境变量了，所以不生效。我猜的。

**Comment by Payne-Wang** [comment]
> 对话码不是很容易过么，怎么你这还出码了

大佬，我试过了，用了ninja run中的参数后可以调用yescaptcha，但是我看帮助文档readme里面有下面三个参数，在容器ninja run help文档中只有第一个，后两个没有，尤其是第三个，因为我的账号是共享的，经常跳5个图片。请问是还没有更新过去嘛？
![image](https://github.com/gngpp/ninja/assets/44337721/ab7c44fc-45c4-4dd7-9898-986eeecd7820)

**Comment by gngpp** [comment]
今天可能更新
