### ISSUE TITLE
0.9.13版本不支持fcsrv，自己编译新版登陆按钮无法点击

### ISSUE THREAD

**Issue by hsea** [gngpp/ninja#467]
尝试自己编译新版本可以支持fcsrv，其它功能都能用，但登陆按钮、获取session按钮无法点击（不出小手的按钮，点了没反应，像是一个文本框而不是一个按钮），不知道是什么原因

用回0.9.13版本，可以登陆和获取session，但不支持fcsrv，辛苦作者有空更新

/etc/ninja$ uname -a
Linux DMIT-LAX2024 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

:/etc/ninja$ ninja run -C serve.toml
Error: TOML parse error at line 17, column 17
   |
17 | arkose_solver = "fcsrv"
   |                 ^^^^^^^
unknown variant `fcsrv`, expected `yescaptcha` or `capsolver`

**Comment by gngpp** [comment]
有些代码我闭源了，不然很快就被arkose修复了

**Comment by hsea** [comment]
原来如此，那我就不尝试重新编译了，期待作者更新编译好的文件

**Comment by hsea** [comment]
> 有些代码我闭源了，不然很快就被arkose修复了

请问目前通过什么方式能用上新版程序啊？之前好像看到发布了新版，但目前release里面只能找到0.9.13

看代码有0.9.16，但自己编译的登陆按钮用不了，有没有可能把闭源部分代码预编译好，剩下的自己编译啊？

或者docker版本具有最新版功能不？

**Comment by gngpp** [comment]
> > 有些代码我闭源了，不然很快就被arkose修复了
> 
> 请问目前通过什么方式能用上新版程序啊？之前好像看到发布了新版，但目前release里面只能找到0.9.13
> 
> 看代码有0.9.16，但自己编译的登陆按钮用不了，有没有可能把闭源部分代码预编译好，剩下的自己编译啊？
> 
> 或者docker版本具有最新版功能不？

现在应该能用了，我整考虑发布.so提供编译
