### ISSUE TITLE
ipv6 子网配置

### ISSUE THREAD

**Issue by heurainbow** [gngpp/ninja#471]
有几个问题请教：
1 vps有ipv6 /64（已分配了一个静态IP地址），但是我直接将X:Y:U:V::/64作为proxies传入后，可以显示All | IPv6 subnet:  bind成功。但是发起请求会超时，感觉是没有通过子网成功发送。
2 我把vps ipv6 /64段内的几个IP静态化配置后，假设配置了10个IPv6，然后把这些IPv6的地址一起作为proxies参数传入，是可以正常使用的。
3 看代码只发现sysctl_route_add_ipv6_subnet这个函数，实现了`ip -6 route add local [IPv6_SUBNET] dev lo`这样的功能。是否我需要在VPS额外配置什么东西才可以使用X:Y:U:V::/64这种模式。

**Comment by gngpp** [comment]
你确定你是子网真的有分配路由吗？先用curl --interface 测试你的子网是不是真的能用。vps子网路由下发配置不在本项目范畴

**Comment by gngpp** [comment]
`ip -6 route add local [IPv6_SUBNET] dev lo` 是自动配置子网路由，你的供应商真的给你下发子网路由才有用

**Comment by gngpp** [comment]
openai限速根据/64限速，如果没有/29 /32 /48 还是不要整了

**Comment by heurainbow** [comment]
有没有推荐可用的vps支持/48的，是不是要先设置ip -6 route add local [IPv6_SUBNET] dev lo 再用curl测试，测试的时候是直接输/48的子网还是一个具体子网内的ip，有没有参考资料供研究

**Comment by gngpp** [comment]
https://zu1k.com/posts/tutorials/http-proxy-ipv6-pool/
