### ISSUE TITLE
希望大佬更新ui在有空的时候

### ISSUE THREAD

**Issue by DR-lin-eng** [gngpp/ninja#472]
1.新ui新增适配了纯中文模式
![image](https://github.com/gngpp/ninja/assets/52230594/e9ba0dff-912b-4a40-a01d-bc8f97f3d42f)
2.新特性
![image](https://github.com/gngpp/ninja/assets/52230594/39da9bb1-a7ee-44f3-b656-143a39a8c956)
3.gtps
![image](https://github.com/gngpp/ninja/assets/52230594/e52aa895-f5da-424d-a484-7f8933aea384)
十分感谢大佬的更新

**Comment by heurainbow** [comment]
建议该项目完全废弃前端和UI的转发，只保留后端和认证相关的转发，要不然项目很快就会被盯上和针对。

**Comment by gngpp** [comment]
> 建议该项目完全废弃前端和UI的转发，只保留后端和认证相关的转发，要不然项目很快就会被盯上和针对。

我也有这种想法，不太想一直更新前端，专注接口服务好了，UI这东西交给别人
