### ISSUE TITLE
【请教】防止被恶意请求

### ISSUE THREAD

**Issue by nankaine** [gngpp/ninja#475]
周末机器被恶意请求了。 
看了下`auth-key`，没看明白具体适用范围。
特来请教一下怎么规避这个情况。

**Comment by gngpp** [comment]
登录用的，所有接口 可以使用白名单，--visitor-email-whitelist，文档写的明明白白

**Comment by gngpp** [comment]
应该是`visitor_email_whitelist`
toml字段格式都是下划线的，不是横杠`-`

**Comment by gngpp** [comment]
是一个数组啊，visitor_email_whitelist = ["admin@ink2test.link"]

**Comment by gngpp** [comment]
好歹要了解一下toml文件的格式

**Comment by gngpp** [comment]
<img width="817" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/e8298bfa-e68d-4a0b-83c4-f3d14e4c860f">
