### ISSUE TITLE
官网ui如何实现

### ISSUE THREAD

**Issue by yfh667** [gngpp/ninja#480]
现在部署的ui还是老的界面，我想自己去学着把相关的web ui扒下来搞到ninja上去。但我之前只搞过古老版本pandora的python源码，ninja项目是rust写的，我是否也是照着把ui弄下来然后与rust源码搞一起，匹配上相关接口，编译就可以了呢

**Comment by gnmdnd384** [comment]
嘴巴一张，就要做这个做那个，连个谢谢都没有，甚至都没有称呼。你是大爷。

**Comment by xiaosaaaa** [comment]
> 嘴巴一张，就要做这个做那个，连个谢谢都没有，甚至都没有称呼。你是大爷。

 人说的是自己做，你眼睛瞎的？

**Comment by gnmdnd384** [comment]
> > 嘴巴一张，就要做这个做那个，连个谢谢都没有，甚至都没有称呼。你是大爷。
> 
> 人说的是自己做，你眼睛瞎的？

那他有本事就自己做啊，说出来干啥。你眼睛好，看到他的语气是有称呼吗？有谢谢吗？开源社区就是被你们这群人搞坏的

**Comment by xiaosaaaa** [comment]
> > > 嘴巴一张，就要做这个做那个，连个谢谢都没有，甚至都没有称呼。你是大爷。
> > 
> > 
> > 人说的是自己做，你眼睛瞎的？
> 
> 那他有本事就自己做啊，说出来干啥。你眼睛好，看到他的语气是有称呼吗？有谢谢吗？开源社区就是被你们这群人搞坏的

你在叫你妈呢，傻狗。

**Comment by gnmdnd384** [comment]
> > > > 嘴巴一张，就要做这个做那个，连个谢谢都没有，甚至都没有称呼。你是大爷。
> > > 
> > > 
> > > 人说的是自己做，你眼睛瞎的？
> > 
> > 
> > 那他有本事就自己做啊，说出来干啥。你眼睛好，看到他的语气是有称呼吗？有谢谢吗？开源社区就是被你们这群人搞坏的
> 
> 你在叫你妈呢，傻狗。

你准备封号吧，投诉了
<img width="958" alt="image" src="https://github.com/gngpp/ninja/assets/133521363/d86680e0-79d9-46e0-b95f-c0b291901523">

**Comment by xiaosaaaa** [comment]
吓死我了

**Comment by xiaosaaaa** [comment]
> > > > > 嘴巴一张，就要做这个做那个，连个谢谢都没有，甚至都没有称呼。你是大爷。
> > > > 
> > > > 
> > > > 人说的是自己做，你眼睛瞎的？
> > > 
> > > 
> > > 那他有本事就自己做啊，说出来干啥。你眼睛好，看到他的语气是有称呼吗？有谢谢吗？开源社区就是被你们这群人搞坏的
> > 
> > 
> > 你在叫你妈呢，傻狗。
> 
> 你准备封号吧，投诉了 <img alt="image" width="958" src="https://private-user-images.githubusercontent.com/133521363/300665604-d86680e0-79d9-46e0-b95f-c0b291901523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODM5MzMsIm5iZiI6MTcwNjU4MzYzMywicGF0aCI6Ii8xMzM1MjEzNjMvMzAwNjY1NjA0LWQ4NjY4MGUwLTc5ZDktNDZlMC1iOTVmLWMwYjI5MTkwMTUyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMzAwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTNmNDQwNmM5ZjI1Njc4OGViMDhiZDhiNTZmNTI0NWIwZGI5Y2U5NDE5MjAxOWNmNzc1MWJkODVhYjA0MTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9HZEOOrJfqUZMIplnn1h8kfjmAzLmeezGG5UYHkkmbs">

吓死我了

**Comment by yfh667** [comment]
翻了下issue，作者给出说法了

**Comment by huangsheng7271** [comment]
我会，嘿嘿
