### ISSUE TITLE
大佬，有没有在VPS的部署教程啊，希望发一下哦，我给您点满星点赞

### ISSUE THREAD

**Issue by xkdopod** [gngpp/ninja#487]
大佬，有没有在VPS的部署教程啊，希望发一下哦，我给您点满星点赞

**Comment by gebederry** [comment]
无，此项目不是面向小白用户的

**Comment by gngpp** [comment]
没有，小白要做足功课

**Comment by Yanyutin753** [comment]
https://apifox.com/apidoc/shared-4b9a7517-3f80-47a1-84fc-fcf78827a04a/doc-3679495

**Comment by Yanyutin753** [comment]
我写了一个 国外的 你可以看看

**Comment by Jacky-Bruse** [comment]
> https://apifox.com/apidoc/shared-4b9a7517-3f80-47a1-84fc-fcf78827a04a/doc-3679495

你好，感谢教程，有个问题想请教，serve.toml内的
pcert = "ca/cert.crt"
pkey = "ca/key.pem"
