### ISSUE TITLE
刚开始还运行正常，过了一会再打开就提示这个错误，怎么解决哈各位大佬们

### ISSUE THREAD

**Issue by xkdopod** [gngpp/ninja#489]
浏览器再打开这个，用的谷歌浏览器。Application error: a client-side exception has occurred (see the browser console for more information).    重启服务都不行

**Comment by xiaosaaaa** [comment]
账号问题，之前的issus你看看啊

**Comment by gngpp** [comment]
UI问题 等更新就对了

**Comment by xkdopod** [comment]
好的，谢谢大佬

**Comment by gngpp** [comment]
In progress: https://github.com/gngpp/ninja/actions/runs/7754567580, has been updated to the latest UI
