### ISSUE TITLE
您登陆的似乎不是oai运营的网站，您的账号可能已经被盗，请登陆修改密码

### ISSUE THREAD

**Issue by Github-CJX** [gngpp/ninja#490]
请问有遇到这个问题的吗？

**Comment by Github-CJX** [comment]
无论是获取token或者直接登录都是这个问题

**Comment by sisancnok13** [comment]
遇到了。回退913版本。正常。916被识别

**Comment by Github-CJX** [comment]
> 遇到了。回退913版本。正常。916被识别

感谢老铁

**Comment by gngpp** [comment]
在修了

**Comment by Github-CJX** [comment]
> 在修了

我丢，佬！

**Comment by GavinGoo** [comment]
+1，上一个版本正常。先自行回退，等大佬修吧

**Comment by gngpp** [comment]
如果没问题就不要随便更新了，先看更新日志

**Comment by imvmi** [comment]
其实我在 0.9.13 版本也碰到了这个问题 #455 
我怀疑是 arkose 的新检测模式，但是也不能确定

**Comment by gngpp** [comment]
是因为检测版本，概率问题，抽查的。有些人没事

**Comment by TimchaStudio** [comment]
我也是同样的问题。

**Comment by chawaa** [comment]
me too！

**Comment by gngpp** [comment]
先回退913版本憋，反正也没什么大更新，要等一阵子

**Comment by gngpp** [comment]
In progress: https://github.com/gngpp/ninja/actions/runs/7754567580, has been updated to the latest UI
