### ISSUE TITLE
请求/backend-api/files接口报500错误

### ISSUE THREAD

**Issue by Payne-Wang** [gngpp/ninja#491]
大佬好，今天在请求/backend-api/files接口时报500错误，Internal Server Error，这个功能昨天还可以使用，不知是否跟pandora关服有关？

![image](https://github.com/gngpp/ninja/assets/44337721/93bc41bd-d4e5-44c8-95a0-7e50b410efcb)

另外，我测试了其它会话接口，均是正常的，唯独上传文件这边有问题，请大佬看看，感谢
![image](https://github.com/gngpp/ninja/assets/44337721/a1b54f45-703e-4166-b2ff-c679bfe595c2)

**Comment by gngpp** [comment]
给我看看500 返回什么消息

**Comment by Payne-Wang** [comment]
500错误返回{"detail":"Internal Server Error"}

我服务器上的ninja接的是pandoratov1api，下面是pandoratov1api在29号和31号的日志，期间pandoratov1api和ninja都没有更新

1月29号传文件没有问题，且/backend-api/files正常：200
![image](https://github.com/gngpp/ninja/assets/44337721/89516e83-1154-491e-a3a5-337dc8653359)

1月29号传文件报错，且/backend-api/files报错：500
![image](https://github.com/gngpp/ninja/assets/44337721/2d62c6c7-e207-463f-b31d-b4c1627cb0a3)

**Comment by yongman** [comment]
测试正常。

**Comment by gngpp** [comment]
很明显就是校验参数了，没填完

**Comment by Payne-Wang** [comment]
> 很明显就是校验参数了，没填完

请大佬具体说一下

**Comment by Payne-Wang** [comment]
这个是我的完整请求：
![image](https://github.com/gngpp/ninja/assets/44337721/be520030-00ca-4e8c-b265-7cc05435d1fc)

**Comment by Payne-Wang** [comment]
大佬，这个问题找到原因了，是账号问题，我是用的账号是共享号，换成自充的非共享号就没问题了。

另外请问，这种共享号和自充号openai那边有检测机制嘛？我咨询了几个用自建逆向搭站的人，他们的gpt-4-all使用的也是共享号，但是上传文件、识图什么的都正常，不过他们的代码闭源不方便询问。ninja是否有可能解决这种检测，目前很多人的号都是共享的，使用成本低一些。

感谢大佬！

**Comment by gngpp** [comment]
那种类型共享号？，你是说team bug号吗，问问楼上那个功夫熊猫就知道了

**Comment by gngpp** [comment]
你联系楼上的功夫熊猫给你测试共享号，我暂时没空

**Comment by yongman** [comment]
> 那种类型共享号？，你是说team bug号吗，问问楼上那个功夫熊猫就知道了

楼上的功夫熊猫也没有 team bug 号，正儿八经的 team 号。:-)

**Comment by Payne-Wang** [comment]
@yongman 老哥，方便测试的话给个邮箱我发给你
