### ISSUE TITLE
大佬，已给星星，请问是不是我配置出问题了，登录接口好像用不了，其他都是正常的，gpt4和gpt4-all都可以使用

### ISSUE THREAD

**Issue by Yanyutin753** [gngpp/ninja#493]
<img width="607" alt="屏幕截图 2024-01-31 202556" src="https://github.com/gngpp/ninja/assets/132346501/f4f2f94f-feb4-4f4d-bf35-444c5cce30ad">

报这个错误

**Comment by gngpp** [comment]
出码了，现在打码还需要验证tguess

**Comment by Yanyutin753** [comment]
最新的，上传了4的har
<img width="421" alt="屏幕截图 2024-01-31 204512" src="https://github.com/gngpp/ninja/assets/132346501/1243d507-429c-46c2-8380-5f0da1823970">

**Comment by Yanyutin753** [comment]
是不是要上传到登录

**Comment by gngpp** [comment]
你可以上网页/har/upload上传，Auth那个就是登录
<img width="872" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/d0e88e21-f5cb-4a4d-a73c-07c4a87356e8">

**Comment by Yanyutin753** [comment]
<img width="512" alt="屏幕截图 2024-01-31 205619" src="https://github.com/gngpp/ninja/assets/132346501/c67c6add-d279-4851-a3a0-949acaf1a376">
<img width="455" alt="屏幕截图 2024-01-31 205643" src="https://github.com/gngpp/ninja/assets/132346501/ddcecfc8-ed37-4fad-bf3f-174a4cb51e32">
谢谢大佬，现在上传了，但是现在postman请求，一直没反应

<img width="660" alt="image" src="https://github.com/gngpp/ninja/assets/132346501/f4e0efb1-d06a-450e-9a0b-3f6840fcac3f">
我的web显示这个

**Comment by Yanyutin753** [comment]
![image](https://github.com/gngpp/ninja/assets/132346501/844d7841-b4dc-4f2d-9415-7879c14c7fab)


显示这个

**Comment by gngpp** [comment]
没救了，看看日志

**Comment by Yanyutin753** [comment]
{"log":"\u001b[2m2024-01-31T13:26:54.354073Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[1mrequest\u001b[0m\u001b[1m{\u001b[0m\u001b[3mmethod\u001b[0m\u001b[2m=\u001b[0mPOST \u001b[3muri\u001b[0m\u001b[2m=\u001b[0m/auth/token \u001b[3mversion\u001b[0m\u001b[2m=\u001b[0mHTTP/1.1\u001b[1m}\u001b[0m\u001b[2m:\u001b[0m \u001b[2mtower_http::trace::on_request\u001b[0m\u001b[2m:\u001b[0m started processing request\n","stream":"stdout","time":"2024-01-31T13:26:54.35428299Z"}
{"log":"\u001b[2m2024-01-31T13:26:56.384589Z\u001b[0m \u001b[33m WARN\u001b[0m \u001b[1mrequest\u001b[0m\u001b[1m{\u001b[0m\u001b[3mmethod\u001b[0m\u001b[2m=\u001b[0mPOST \u001b[3muri\u001b[0m\u001b[2m=\u001b[0m/auth/token \u001b[3mversion\u001b[0m\u001b[2m=\u001b[0mHTTP/1.1\u001b[1m}\u001b[0m\u001b[2m:\u001b[0m \u001b[2mopenai::auth::provide::web\u001b[0m\u001b[2m:\u001b[0m [crates/openai/src/auth/provide/web.rs:177:13] WebAuthProvider::authenticate_password: invalid location path: https://chat.openai.com/\n","stream":"stdout","time":"2024-01-31T13:26:56.384734095Z"}
{"log":"\u001b[2m2024-01-31T13:26:56.384844Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[1mrequest\u001b[0m\u001b[1m{\u001b[0m\u001b[3mmethod\u001b[0m\u001b[2m=\u001b[0mPOST \u001b[3muri\u001b[0m\u001b[2m=\u001b[0m/auth/token \u001b[3mversion\u001b[0m\u001b[2m=\u001b[0mHTTP/1.1\u001b[1m}\u001b[0m\u001b[2m:\u001b[0m \u001b[2mtower_http::trace::on_response\u001b[0m\u001b[2m:\u001b[0m finished processing request \u001b[3mlatency\u001b[0m\u001b[2m=\u001b[0m2030 ms \u001b[3mstatus\u001b[0m\u001b[2m=\u001b[0m400\n","stream":"stdout","time":"2024-01-31T13:26:56.384917295Z"}

![image](https://github.com/gngpp/ninja/assets/132346501/f0098673-da43-4924-9266-f5f038adf0d1)

`{
    "code": 400,
    "msg": "Accidentally jumped back to the login homepage, please try again."
}`

**不行，我刚刚换Releases也不行，**

**Comment by Yanyutin753** [comment]
辛苦大佬了，维护不易，不行我就爬f12，搞个自动爬的，其他都能用

**Comment by gngpp** [comment]
arkose/ip有问题时才会跳首页，你加上启动参数`--enable-arkose-proxy`，然后http://127.0.0.1:7999/auth/arkose_token/0A1D34FC-659D-4E23-B17B-694DCFCF6A6C，看看有没有sup=1就知道了

**Comment by gngpp** [comment]
yes，arkose是sup

**Comment by wt5512** [comment]
新出的Gpt验证码 获取Arkose接口：
```
curl --location --request POST 'https://app.westpaas.com/BaseService/api/Gpt/UseGptArkoseBatch?count=1' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjgwNUYyMTIyQkVERENENkRDQjFGRjI3OTQ2OTI1OEJBIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MDY1MTA4NjcsImV4cCI6MTcwOTEwMjg2NywiaXNzIjoiaHR0cDovL2FwcC53ZXN0cGFhcy5jb20vYXV0aCIsImNsaWVudF9pZCI6InNob3V6dWFwaSIsInN1YiI6IjZjOTcxYjkyLWI2MGMtNGY0Ny1hZmNkLWYxZGQ3NzdkM2E1NCIsImF1dGhfdGltZSI6MTcwNjUxMDg2NywiaWRwIjoibG9jYWwiLCJuYW1lIjoiZmRfMjIwMzAzMTcwNTEwXzEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJmZF8yMjAzMDMxNzA1MTBfMUBtYWlsLmNvbSIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiWVQ2WU5EREFVQ1JMQzVUWVpSNEFQQVI2WUg3SEoyRDciLCJ3eG9wZW5pZF93eDQ2M2E0M2E4YjY4Y2MzOTAiOiJvaHNNZzZhLUZUbVN3R2F5dV9Fa0I5OXNrd3NvIiwiQ2xpZW50SWQiOiJzaG91enVhcGkiLCJVc2VyRGF0YSI6IntcIlNpZFwiOlwiZTQyMmMxYTBiMTMzNDcxYWE2NjVkZjBmNDc3ZTkzNjJcIixcIlVzZXJJZFwiOlwiNmM5NzFiOTItYjYwYy00ZjQ3LWFmY2QtZjFkZDc3N2QzYTU0XCIsXCJVc2VyTmFtZVwiOlwiZmRfMjIwMzAzMTcwNTEwXzFcIixcIkVtYWlsXCI6XCJmZF8yMjAzMDMxNzA1MTBfMUBtYWlsLmNvbVwiLFwiTW9iaWxlXCI6XCIxODYyOTUwMDIzOFwiLFwiV3hPcGVuSWRzXCI6W3tcIlVzZXJJZFwiOlwiNmM5NzFiOTItYjYwYy00ZjQ3LWFmY2QtZjFkZDc3N2QzYTU0XCIsXCJXeEFwcElkXCI6XCJ3eDQ2M2E0M2E4YjY4Y2MzOTBcIixcIld4T3BlbklkXCI6XCJvaHNNZzZhLUZUbVN3R2F5dV9Fa0I5OXNrd3NvXCJ9XX0iLCJqdGkiOiI1QUYzQkMyNTUzOUIyNDU1MDRBNDlFMzg5M0MyMjNDQiIsImlhdCI6MTcwNjUxMDg2Nywic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInNob3V6dWFwaSJdLCJhbXIiOlsid3giXX0.Zjp19VdKZJz7Xy7Pm8fuVz050dApBa-eIq5a3CIO5NDBWMh0bn0CpKu4d3dMtjD_vY8ssfSn_WQn7geZDBsTxbyVKxDHrjbZGAlmntCVqPjflRW2WT8sjrYQIB1mCZtL4JwYo9Wx68-tpAMtnk8bjo8NDjZd-nXiAeXgizAHcvqhWuge1j4e1ssA-nsLeQDAEYWmSLL5Qe1MAdGjjBLsd0PKdfFqfDH4q2CauhuCirCEGIgDCMX9MwjiirCaYE0eYp0T4jVrNr6x5tFQsZdaegv-1obh9hUU7kyOne7NO0UBjlkGU6k9ZJ18A7wzcYE8oMNRgOi5emSuhQGzMbaLew'
```

**Comment by wt5512** [comment]
arkose最新接口
![image](https://github.com/gngpp/ninja/assets/7941052/b4c064f2-d350-4e7e-aee8-18c7331dd056)
chatgpt-arkose-token-api-next
