### ISSUE TITLE
请问 /auth/token 返回 code 500 怎么解决

### ISSUE THREAD

**Issue by duansix** [gngpp/ninja#494]
{"code":500,"msg":"error sending request for url (https://chat.openai.com/api/auth/signin/auth0?prompt=login): error trying to connect: TLS handshake failed: cert verification failed - Invalid certificate verification context unexpected EOF"}

serve.toml 开启了 proxy
arkose-solver: yescaptcha

**Comment by duansix** [comment]
TLS是配置 localhost的证书？

**Comment by nekomiya-hinata** [comment]
这个一般都是节点问题，不是节点没解锁gpt就是节点挂掉了

**Comment by gngpp** [comment]
最近别打码了，没有tguess服务 打了 openai也不会认的，自建我不会公开，服务器顶不住。

**Comment by duansix** [comment]
那就是只能抓har吗

**Comment by gngpp** [comment]
不想折腾可以玩这个，我的项目本来不是面向开箱即用的群体

xyhelper重要源码及相关信息

——————
CockroachAi（又名蟑螂）
官网ui，用于账号共享，免费但暂不开源。独立部署，不过我们网关。无频率限制。
https://github.com/cockroachai/cockroachai
——————
官网账号登录
直接使用地址:
https://chat.freegpts.org/
免翻，官网最新ui，支持team号，支持gpts
自己部署反代地址:https://freegpts.org/
——————
获取refreshCookie(session-token): https://chat.freegpts.org/getsession
获取refreshToken地址: https://chat.freegpts.org/applelogin
更多仓库请关注 https://github.com/xyhelper
——————
注:
1.蟑螂和freegpts为公益项目，免费没有付费项。

**Comment by gngpp** [comment]
> 那就是只能抓har吗 

抓了也没啥用 万一出码就只能干瞪着
