### ISSUE TITLE
这是ip被ban了吗？

### ISSUE THREAD

**Issue by lxyanlove** [gngpp/ninja#498]
{
  "error": {
    "message": "当前分组上游负载已饱和，请稍后再试 (request id: 2024020118022617175502YCEL5Sjv)",
    "type": "upstream_error",
    "param": "429",
    "code": "bad_response_status_code"
  }
}

**Comment by spacex-3** [comment]
+10086

**Comment by gngpp** [comment]
没有明确消息看不到，429正确来说就是IP发多消息限制了
