### ISSUE TITLE
请问项目支持新版的webui吗？我部署好看了下UI是旧版的，不支持gpts

### ISSUE THREAD

**Issue by rango886** [gngpp/ninja#503]
请问项目支持新版的webui吗？我部署好看了下UI是旧版的，不支持gpts

**Comment by cleverhu** [comment]
https://github.com/gngpp/ninja/pull/501 参考这个pr，可以等，也可以临时部署，解决一下

**Comment by gngpp** [comment]
In progress: https://github.com/gngpp/ninja/actions/runs/7754567580, has been updated to the latest UI
