### ISSUE TITLE
backend-api conversation在response中不再返回内容

### ISSUE THREAD

**Issue by heurainbow** [gngpp/ninja#504]
http://{{host}}/backend-api/conversation 的响应不再返回内容，而是返回
{
    "wss_url": "wss://chatgpt-async-webps-prod-eastus-7.webpubsub.azure.com/client/hubs/XXXX",
    "expires_at": "2024-02-02T03:37:10.002621+00:00",
    "conversation_id": "b8f710e2-1368-4d37-aa20-5bf6cc1c91aa",
    "response_id": "84ef0cf0deeb2615-NRT"
}

请大佬看看如何解决

**Comment by kinolle** [comment]
同样有这个问题

**Comment by gngpp** [comment]
出Web socket了 没有适配

**Comment by ningvw520** [comment]
我也碰到了 debug了半天 感情大家都一样 捂脸

**Comment by GitHubChrisChen8035** [comment]
你们都是怎么看的返回？

**Comment by RockyZ** [comment]
> 你们都是怎么看的返回？

F12

**Comment by leezhuuu** [comment]
作者有适配计划吗，加油作者

**Comment by gngpp** [comment]
这个搞起来有点费劲，除了chat2api外应该是让客户端去实现的。cws那边在搞了

**Comment by King-Of-Knights** [comment]
@gngpp 大大好呀，我用的是ninja+lss233+GPT3.5+go-cqhttp，用ws端口反向代理的，今天也是看到chatgpt网页有QQ相应的对话，但是没有返回的内容，是不是和这个问题一样呢？

**Comment by gngpp** [comment]
是的，openai改对话协议了，返回的wss接口需要客户端去连接对话。

**Comment by King-Of-Knights** [comment]
@gngpp 那就是lss233这些客户端进行升级，主动调整对话协议了

**Comment by Lyn6969** [comment]
> 这个搞起来有点费劲，除了chat2api外应该是让客户端去实现的。cws那边在搞了

怪不得我的chat2api也出问题了。。。我还找了好久的问题

**Comment by JimEverest** [comment]
请问有什么快速适配新协议的办法吗？

**Comment by heurainbow** [comment]
> 这个搞起来有点费劲，除了chat2api外应该是让客户端去实现的。cws那边在搞了

cws已经实现了。本项目是否还考虑实现？

**Comment by gngpp** [comment]
> > 这个搞起来有点费劲，除了chat2api外应该是让客户端去实现的。cws那边在搞了
> 
> cws已经实现了。本项目是否还考虑实现？

只考虑转发，to api可能会做一下。没时间就算了

**Comment by heurainbow** [comment]
已经采用cws的方案，暂时先关闭了，等大佬支持toapi

**Comment by heurainbow** [comment]
> 大佬，cws是啥，可以麻烦解释一下吗

https://github.com/chatpire/chatgpt-web-share

**Comment by CharlieSeastar** [comment]
> > 大佬，cws是啥，可以麻烦解释一下吗
> 
> https://github.com/chatpire/chatgpt-web-share



> > 大佬，cws是啥，可以麻烦解释一下吗
> 
> https://github.com/chatpire/chatgpt-web-share
非常感谢！

**Comment by CharlieSeastar** [comment]
> > 大佬，cws是啥，可以麻烦解释一下吗
> 
> https://github.com/chatpire/chatgpt-web-share

非常感谢！
