### ISSUE TITLE
您登录的网站似乎不是由 OpenAI 运营的。您的密码可能已被盗。请访问 openai.com 并重置您的密码。

### ISSUE THREAD

**Issue by wozuiyangqi** [gngpp/ninja#505]
版本0.93
用ip：port方式正常登录
用nginx代理后报错。大佬方便在文档上补充一个nginx代理配置吗
附上报错配置

**Comment by wozuiyangqi** [comment]
server {
        listen       443 ssl;
        server_name  xx.com;
        ssl_certificate      /usr/local/nginx/ssl/xx.pem;
        ssl_certificate_key  /usr/local/nginx/ssl/xx.key;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:1m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 SSLv2 SSLv3;
        ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
        ssl_prefer_server_ciphers on;
        ssl_verify_client off;
        add_header Access-Control-Allow-Origin *;
        location / {
                proxy_http_version     1.1;
                proxy_pass              http://localhost:7999;
                proxy_set_header       Connection              "";
                proxy_set_header       Host                    $http_host;
                proxy_set_header       X-Forwarded-Proto       $scheme;
                proxy_set_header       X-Real-IP               $remote_addr;
                proxy_set_header       X-Forwarded-For         $proxy_add_x_forwarded_for;

                proxy_buffering off;
                proxy_cache off;

                send_timeout 600;
                proxy_connect_timeout 600;
                proxy_send_timeout 600;
                proxy_read_timeout 600;
        }
            }

**Comment by gngpp** [comment]
不知道捏，看看有没有人回答你吧

**Comment by Github-CJX** [comment]
#490 这个问题提出过一次了，可以等待后续版本或者先用以前0.9.13版本

**Comment by Github-CJX** [comment]
如果有宝塔的话可以一键添加反代，不用改配置，用默认的就行，至少我是这样用的，默认配置是这样的

#PROXY-START/

location ^~ /
{
    proxy_pass http://172.20.0.4:7999;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;

    #Set Nginx Cache
    
    
    set $static_filecuGqiyis 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
    	set $static_filecuGqiyis 1;
    	expires 1m;
        }
    if ( $static_filecuGqiyis = 0 )
    {
    add_header Cache-Control no-cache;
    }
}

#PROXY-END/

**Comment by wozuiyangqi** [comment]
我试了一下 然而并不行 不知道是不是因为挂了域名的问题。

**Comment by kuperxu** [comment]
> 我试了一下 然而并不行 不知道是不是因为挂了域名的问题。

加了 CF 了吗
