### ISSUE TITLE
docker 更新  gngpp/ninja:latest (v0.9.20) 后，ChatGPT WebUI 使用 access-token 无法登录

### ISSUE THREAD

**Issue by tanquan** [gngpp/ninja#506]
docker 更新  gngpp/ninja:latest (TAG 0.9.20) 后，ChatGPT WebUI 使用 access-token 无法登录
报错：Error
invalid access-token

回退使用 gngpp/ninja:latest (TAG 0.9.16)，ChatGPT WebUI 可以正常使用 access-token 登录。

**Comment by VectorZhao** [comment]
+1

**Comment by gngpp** [comment]
已经不支持access token登录 只能直登/或者用session token
