### ISSUE TITLE
how to run linux action in fork repo please guide step by step

### ISSUE THREAD

**Issue by Niansuh** [gngpp/ninja#507]
how to run linux action in fork repo please guide step by step

![image](https://github.com/gngpp/ninja/assets/139365289/38089535-a21f-4cbc-9bb5-8ae6604e1e0e)

![image](https://github.com/gngpp/ninja/assets/139365289/9ed7e7b4-973e-46df-86f1-89835cb1702d)

**Comment by gngpp** [comment]
My key code is closed source. Even if you compile it successfully, it is of no use.

**Comment by Niansuh** [comment]
the macos is deployed without any key
