### ISSUE TITLE
Token无效

### ISSUE THREAD

**Issue by voctot** [gngpp/ninja#508]
![1706930081034](https://github.com/gngpp/ninja/assets/36097179/1de55029-1072-4726-8315-6bb99e00d1a7)

> 明明输出正确的Token却显示无效，这是为什么？（已经尝试很多次了）

**Comment by gngpp** [comment]
你这是session token吗？网络有问题也是没有任何用的，那个标题提示invalid access token，其实应该是invalid session token，忘记改了

**Comment by voctot** [comment]
那我想应该是网络问题把。

**Comment by voctot** [comment]
不对啊，之前能用的，升级后就tonken无效了....

**Comment by gngpp** [comment]
这么说吧我没有问题，你得用session token 登录。以前登录 用access token 全部失效了。

**Comment by gngpp** [comment]
以后webui 不再支持`access token`/`refresh token`登录使用，只能通过`直登`/`session token`

**Comment by voctot** [comment]
这下可以了，谢谢~  我一直拿的都是access token....
