### ISSUE TITLE
大佬问问,自带web面板也无法返回内容需要刷新查看历史记录才有回答

### ISSUE THREAD

**Issue by DR-lin-eng** [gngpp/ninja#509]
自带web面板也无法返回内容需要刷新查看历史记录才有回答,看了其他回答是否也是因为对话协议修改的问题

**Comment by gngpp** [comment]
我做了缓存。可能是缓存，清空一下就好了，我这边没有任何问题
<img width="1824" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/d9ee4fc1-de4f-451a-8970-3315b15730d1">
gpts 昨天也测了

**Comment by gngpp** [comment]
> 我做了缓存。可能是缓存/网络慢一时半会也不会加载出来，清空一下就好了，我这边没有任何问题 <img alt="image" width="1824" src="https://private-user-images.githubusercontent.com/51810656/302010057-d9ee4fc1-de4f-451a-8970-3315b15730d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzA4MDQsIm5iZiI6MTcwNjkzMDUwNCwicGF0aCI6Ii81MTgxMDY1Ni8zMDIwMTAwNTctZDllZTRmYzEtZGU0Zi00NTFhLTg5NzAtMzMxNWIxNTczMGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAzMjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODk1NmY5MmE0NDllNjc2Mjk5MzM1YjE0MjgxMWJkYWEyNzJlM2U2ZjU1NTg0MzlmNTNjZjQ5YmE1ODM5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_mHEG4O3BgdRa4awBy48hUOvPT2NYves_ZbfnFjwKw"> gpts 昨天也测了

**Comment by DR-lin-eng** [comment]
okok

**Comment by DR-lin-eng** [comment]
话说大佬这是更新ui了?

**Comment by gngpp** [comment]
> 话说大佬这是更新ui了?

偷偷更新了

**Comment by DR-lin-eng** [comment]
哈哈哈,什么时候下放给我们玩玩{狗头}
![image](https://github.com/gngpp/ninja/assets/52230594/34975bb7-d0d0-4c10-ac8a-1bc9b0d39406)

**Comment by gngpp** [comment]
0.9.20就是最新的

**Comment by DR-lin-eng** [comment]
> 0.9.20就是最新的

估计是我服务器抽风了,我去研究一下
