### ISSUE TITLE
大佬,更新过后无法通过nginx反代进行访问,ip访问正常

### ISSUE THREAD

**Issue by DR-lin-eng** [gngpp/ninja#510]
大佬,更新过后无法通过nginx反代进行访问,ip访问正常
我试过了docker和直接部署均不行,旧版本9.13可以
附上docker日志

`[2m2024-02-03T05:40:50.653663Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Create default HAR directory: /root/.ninja/gpt3
[2m2024-02-03T05:40:50.654030Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Start watching HAR directory: /root/.ninja/gpt3
[2m2024-02-03T05:40:50.654369Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Create default HAR directory: /root/.ninja/gpt4
[2m2024-02-03T05:40:50.654625Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Start watching HAR directory: /root/.ninja/gpt4
[2m2024-02-03T05:40:50.654976Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Create default HAR directory: /root/.ninja/auth
[2m2024-02-03T05:40:50.655280Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Start watching HAR directory: /root/.ninja/auth
[2m2024-02-03T05:40:50.655582Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Create default HAR directory: /root/.ninja/platform
[2m2024-02-03T05:40:50.655848Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Start watching HAR directory: /root/.ninja/platform
[2m2024-02-03T05:40:50.656084Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Create default HAR directory: /root/.ninja/signup
[2m2024-02-03T05:40:50.656268Z[0m [32m INFO[0m [2mopenai::context::arkose::har[0m[2m:[0m Start watching HAR directory: /root/.ninja/signup
[2m2024-02-03T05:40:50.726973Z[0m [32m INFO[0m [2mopenai::serve[0m[2m:[0m What is my IP address: 104.28.196.78
[2m2024-02-03T05:40:50.726994Z[0m [32m INFO[0m [2mopenai::context::arkose[0m[2m:[0m Arkose Periodic task is running
[2m2024-02-03T05:40:50.727009Z[0m [32m INFO[0m [2mopenai::serve[0m[2m:[0m Starting HTTP(S) server at http(s)://0.0.0.0:7999
[2m2024-02-03T05:40:50.960088Z[0m [32m INFO[0m [2mopenai::context::arkose[0m[2m:[0m Arkose version: 2.3.5
[2m2024-02-03T05:41:19.458578Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:19.700824Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m242 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:20.001092Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:20.212808Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m211 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:20.757355Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/_next/static/chunks/pages/_app-ee0b14f890279a08.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:20.842548Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/_next/static/chunks/pages/_app-ee0b14f890279a08.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:20.850925Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/chrome-extension:/ibdfeimkglcmdejppabkaidpippniiob/aiscripts/scriptBus.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:20.919505Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/_next/static/chunks/pages/_app-ee0b14f890279a08.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m162 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:20.924811Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/chrome-extension:/ibdfeimkglcmdejppabkaidpippniiob/aiscripts/scriptBus.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m73 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:20.961778Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/_next/static/chunks/pages/_app-ee0b14f890279a08.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m119 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:20.998634Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/service-worker.64e6c253600ea4c3.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:21.078499Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/service-worker.64e6c253600ea4c3.js [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m79 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:31.824676Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:32.065563Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m240 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:41:44.364182Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:41:44.596710Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m232 ms [3mstatus[0m[2m=[0m200
[2m2024-02-03T05:42:04.631393Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_request[0m[2m:[0m started processing request
[2m2024-02-03T05:42:04.871164Z[0m [32m INFO[0m [1mrequest[0m[1m{[0m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/ [3mversion[0m[2m=[0mHTTP/1.1[1m}[0m[2m:[0m [2mtower_http::trace::on_response[0m[2m:[0m finished processing request [3mlatency[0m[2m=[0m239 ms [3mstatus[0m[2m=[0m200
`
直接部署日志
`2024-02-03T05:41:17.564456Z  INFO request{method=POST uri=/v1/chat/completions version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:41:17.688985Z  INFO request{method=POST uri=/v1/chat/completions version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=124 ms status=429
2024-02-03T05:41:19.685905Z  INFO request{method=POST uri=/v1/chat/completions version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:41:19.795056Z  INFO request{method=POST uri=/v1/chat/completions version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=109 ms status=429
2024-02-03T05:44:49.978277Z  INFO request{method=GET uri=/ version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:44:50.437615Z  INFO request{method=GET uri=/ version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=459 ms status=200
2024-02-03T05:44:51.061418Z  INFO request{method=GET uri=/ version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:44:51.269230Z  INFO request{method=GET uri=/ version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=207 ms status=200
2024-02-03T05:44:51.899039Z  INFO request{method=GET uri=/service-worker.js version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:44:51.899086Z  INFO request{method=GET uri=/service-worker.js version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=200
2024-02-03T05:44:52.272010Z  INFO request{method=GET uri=/chrome-extension:/ibdfeimkglcmdejppabkaidpippniiob/aiscripts/scriptBus.js version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:44:52.273658Z  INFO request{method=GET uri=/_next/static/chunks/pages/_app-ee0b14f890279a08.js version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-02-03T05:44:52.345771Z  INFO request{method=GET uri=/chrome-extension:/ibdfeimkglcmdejppabkaidpippniiob/aiscripts/scriptBus.js version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=73 ms status=200
2024-02-03T05:44:52.403535Z  INFO request{method=GET uri=/_next/static/chunks/pages/_app-ee0b14f890279a08.js version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=129 ms status=200
`

**Comment by DR-lin-eng** [comment]
看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载

**Comment by VectorZhao** [comment]
+1
Nginx Proxy Manager反代之后通过域名访问时无法登录，提示502，利用ip:port登录正常。

**Comment by gngpp** [comment]
那是你nginx配置有问题，跟我没关系

**Comment by DR-lin-eng** [comment]
> 那是你nginx配置有问题，跟我没关系

知道留个问题讨论一下,谢谢

**Comment by VectorZhao** [comment]
> 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
我这里浏览器F12会有如下提示：
```
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
    at service-worker.js:1:949
（匿名） @ service-worker.js:1
Promise.then（异步）
（匿名） @ service-worker.js:1
Promise.then（异步）
（匿名） @ service-worker.js:1
Promise.then（异步）
（匿名） @ service-worker.js:1
login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
```

**Comment by DR-lin-eng** [comment]
> > 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
> > 我这里浏览器F12会有如下提示：
> 
> ```
> Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
>     at service-worker.js:1:949
> （匿名） @ service-worker.js:1
> Promise.then（异步）
> （匿名） @ service-worker.js:1
> Promise.then（异步）
> （匿名） @ service-worker.js:1
> Promise.then（异步）
> （匿名） @ service-worker.js:1
> login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
> ```

我也一样我在查问题,在尝试有效果了告诉你

**Comment by DR-lin-eng** [comment]
> > 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
> > 我这里浏览器F12会有如下提示：
> 
> ```
> Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
>     at service-worker.js:1:949
> （匿名） @ service-worker.js:1
> Promise.then（异步）
> （匿名） @ service-worker.js:1
> Promise.then（异步）
> （匿名） @ service-worker.js:1
> Promise.then（异步）
> （匿名） @ service-worker.js:1
> login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
> ```

![image](https://github.com/gngpp/ninja/assets/52230594/6bf27331-7d08-471e-aff6-00de9b2aabc3)
这是ai回答,正在按照这个方向去研究

**Comment by VectorZhao** [comment]
> > > 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
> > > 我这里浏览器F12会有如下提示：
> > 
> > 
> > ```
> > Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
> >     at service-worker.js:1:949
> > （匿名） @ service-worker.js:1
> > Promise.then（异步）
> > （匿名） @ service-worker.js:1
> > Promise.then（异步）
> > （匿名） @ service-worker.js:1
> > Promise.then（异步）
> > （匿名） @ service-worker.js:1
> > login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
> > ```
> 
> 我也一样我在查问题,在尝试有效果了告诉你

好的，谢谢。不知道这个issue有没有参考价值
https://github.com/gngpp/ninja/issues/286
Nginx Proxy Manager我开启了cache assets，不起作用

**Comment by DR-lin-eng** [comment]
> > > > 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
> > > > 我这里浏览器F12会有如下提示：
> > > 
> > > 
> > > ```
> > > Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
> > >     at service-worker.js:1:949
> > > （匿名） @ service-worker.js:1
> > > Promise.then（异步）
> > > （匿名） @ service-worker.js:1
> > > Promise.then（异步）
> > > （匿名） @ service-worker.js:1
> > > Promise.then（异步）
> > > （匿名） @ service-worker.js:1
> > > login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
> > > ```
> > 
> > 
> > 我也一样我在查问题,在尝试有效果了告诉你
> 
> 好的，谢谢。不知道这个issue有没有参考价值 #286 Nginx Proxy Manager我开启了cache assets，不起作用

其实我一直没开缓存,所以应该不是缓存的问题,这是ai的回答:
![image](https://github.com/gngpp/ninja/assets/52230594/05464f6a-2bbe-48cb-b5ac-040b72978670)

**Comment by DR-lin-eng** [comment]
![image](https://github.com/gngpp/ninja/assets/52230594/31d423ee-7ee1-4340-b8af-50aa6315f33c)

**Comment by DR-lin-eng** [comment]
> > > > 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
> > > > 我这里浏览器F12会有如下提示：
> > > 
> > > 
> > > ```
> > > Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
> > >     at service-worker.js:1:949
> > > （匿名） @ service-worker.js:1
> > > Promise.then（异步）
> > > （匿名） @ service-worker.js:1
> > > Promise.then（异步）
> > > （匿名） @ service-worker.js:1
> > > Promise.then（异步）
> > > （匿名） @ service-worker.js:1
> > > login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
> > > ```
> > 
> > 
> > 我也一样我在查问题,在尝试有效果了告诉你
> 
> 好的，谢谢。不知道这个issue有没有参考价值 #286 Nginx Proxy Manager我开启了cache assets，不起作用

ai是这样说的:
这个错误信息表示在尝试使用 Cache API 将一个请求存储到缓存时失败了，因为请求的方案（scheme）是 chrome-extension，这是不被支持的。错误信息中提到的 Uncaught (in promise) TypeError 指的是一个在 Promise 中没有被捕获（即没有通过 .catch() 处理）的类型错误。

**Comment by li88iioo** [comment]
插眼

**Comment by VectorZhao** [comment]
> > > > > 看起来理论上应该访问正常但是实际上只加载了html,css和js文件都没加载
> > > > > 我这里浏览器F12会有如下提示：
> > > > 
> > > > 
> > > > ```
> > > > Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
> > > >     at service-worker.js:1:949
> > > > （匿名） @ service-worker.js:1
> > > > Promise.then（异步）
> > > > （匿名） @ service-worker.js:1
> > > > Promise.then（异步）
> > > > （匿名） @ service-worker.js:1
> > > > Promise.then（异步）
> > > > （匿名） @ service-worker.js:1
> > > > login:1 ServiceWorker registration successful with scope:  https://xxx.xx.xx/
> > > > ```
> > > 
> > > 
> > > 我也一样我在查问题,在尝试有效果了告诉你
> > 
> > 
> > 好的，谢谢。不知道这个issue有没有参考价值 #286 Nginx Proxy Manager我开启了cache assets，不起作用
> 
> ai是这样说的: 这个错误信息表示在尝试使用 Cache API 将一个请求存储到缓存时失败了，因为请求的方案（scheme）是 chrome-extension，这是不被支持的。错误信息中提到的 Uncaught (in promise) TypeError 指的是一个在 Promise 中没有被捕获（即没有通过 .catch() 处理）的类型错误。

搞不懂，
9.13版本是没这个问题的

**Comment by VectorZhao** [comment]
@DR-lin-eng 
曲线救国，
利用cf的tunnels进行隧穿：进入tunnels的主页，复制docker的创建命令，vps上安装tunnels，然后在tunnels主页中配置域名

**Comment by DR-lin-eng** [comment]
> @DR-lin-eng 曲线救国， 利用cf的tunnels进行隧穿：进入tunnels的主页，复制docker的创建命令，vps上安装tunnels，然后在tunnels主页中配置域名

确实是曲线救国,应该没问题这样子

**Comment by GavinGoo** [comment]
在location块加上以下内容试试：
```
proxy_buffering off;
proxy_cache off;
send_timeout 600;
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
proxy_headers_hash_max_size 51200;
proxy_headers_hash_bucket_size 6400;
```

**Comment by gngpp** [comment]
不要给nginx设置乱七八糟的请求头就行了，因为我是直接透传的，设置乱七八糟的请求头直接把你认出来钓鱼了

**Comment by VectorZhao** [comment]
Nginx Proxy Manager
任你怎么点，都无法避免502

**Comment by DR-lin-eng** [comment]
> 不要给nginx设置乱七八糟的请求头就行了，因为我是直接透传的，设置乱七八糟的请求头直接把你认出来钓鱼了

朴实无华的反代
`

location ^~ /
{
    proxy_pass http://127.0.0.1:7999;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_cache off;
    send_timeout 600;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    proxy_headers_hash_max_size 51200;
    proxy_headers_hash_bucket_size 6400;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;

    #Set Nginx Cache
    
    
    set $static_filej3cbPP14 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
    	set $static_filej3cbPP14 1;
    	expires 1m;
        }
    if ( $static_filej3cbPP14 = 0 )
    {
    add_header Cache-Control no-cache;
    }
`
