### ISSUE TITLE
登录/auth/token接口时报DECRYPTION_FAILED_OR_BAD_RECORD_MAC错误

### ISSUE THREAD

**Issue by sk163** [gngpp/ninja#513]
0.9.20版本登录/auth/token接口时报错，之前登录正常过，但后来一直报如下的错误：
{"code":500,"msg":"error sending request for url (https://chat.openai.com/api/auth/csrf): connection error: [BAD_DECRYPT] [DECRYPTION_FAILED_OR_BAD_RECORD_MAC]"}

不知是依赖的ssl库的问题？cf？还是ip的问题呢？使用相同的ip是可以正常登录和使用官方chatgpt的。求大神看看如何解决

**Comment by gngpp** [comment]
看文档 换个指纹，这个接口经常出毛病

**Comment by sk163** [comment]
> 看文档 换个指纹，这个接口经常出毛病，我不知道你是否还使用了透明代理？这个错误我用这么久没见过

请教指纹该如何设置呢？
--impersonate-uas或环境变量配置IMPERSONATE_UA=xxxx都报不支持
比如设置："Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"

会报Unsupport impersonate user agent

**Comment by gngpp** [comment]
原来是软路由，那是你那边解密了我的tls出问题了。透明代理就是这样的，可能会不兼容。获取支持的ua命令`ninja ua`

**Comment by sk163** [comment]
> 原来是软路由，那是你那边解密了我的tls出问题了。透明代理就是这样的，可能会不兼容/你可能需要升级你的代理TLS版本。获取支持的ua命令`ninja ua`

更改了ua后依然报这个错，可能确实是代理的问题，我换成http或socket代理试试，多谢

**Comment by sk163** [comment]
我换了台vps代理，然后就不报DECRYPTION_FAILED_OR_BAD_RECORD_MAC错误了，感觉是openai对之前的ip做什么风控。使用新的ip后，报Accidentally jumped back to the login homepage, please try again这个错误。然后用了您的tguess服务，就成功了！非常感谢！能问下tguess这个是什么服务？做什么用的？
