### ISSUE TITLE
又出现这个错误了 Accidentally jumped back to the login homepage, please try again.

### ISSUE THREAD

**Issue by ynpl** [gngpp/ninja#514]
尝试更换了 har 也是报了这个错误

**Comment by gngpp** [comment]
加上启动参数`--enable-arkose-proxy`，然后`curl http://127.0.0.1:7999/auth/arkose_token/0A1D34FC-659D-4E23-B17B-694DCFCF6A6C`

**Comment by gngpp** [comment]
如果是出码了，你还接了打码，没有tguess服务，打了也没用

**Comment by ynpl** [comment]
> 如果是出码了，你还接了打码，没有tguess服务，打了也没用

加了代理ip池了也接了YES, 主要是上一秒还是正常的. 然后突然不行了 接着就全错了

**Comment by gngpp** [comment]
我公开的tguess接口`https://tguess.2077000.xyz/tguess`，自己填上`--arkose-solver-tguess-endpoint https://tguess.2077000.xyz/tguess`

**Comment by ynpl** [comment]
好的老哥 我尝试下

**Comment by gngpp** [comment]
哦对了如果你是用那种代理请求一次变一次IP的，那么就不适合做arkose代理，你得排除一下。只能用本地`ipv6 subnet`去搞arkose

**Comment by ynpl** [comment]
> 哦对了如果你是用那种代理请求一次变一次IP的，那么就不适合做arkose代理，你得排除一下。只能用本地`ipv6 subnet`去搞arkose
> 
> arkose 打码上下文要求IP一致了

好的谢谢, 我用的按照时长更换的ip.

**Comment by ynpl** [comment]
感谢大佬可以了
