### ISSUE TITLE
/auth/refresh_token接口403错误

### ISSUE THREAD

**Issue by lazzman** [gngpp/ninja#515]
## 复现步骤

1. 调用/auth/token获取refreshTokenA
2. 调用/auth/refresh_token刷新refreshTokenA，ninja此时返回的还是refreshTokenA（实测官方接口返回的是新的refreshTokenB）
3. 再次调用/auth/refresh_token刷新refreshTokenA，ninja此时返回403

## 猜测

官方调整了refresh_token逻辑？每次调用都会返回新的refresh_token？

**Comment by gngpp** [comment]
你发一下官方返回的response 格式我看看，有可能是变了

**Comment by gngpp** [comment]
以前是不会重新生成`refresh token` 
<img width="1186" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/072053f7-0c87-4f1d-99df-6c2c5f62767d">

**Comment by lazzman** [comment]
又测试了一下：
从https://chat.freegpts.org/applelogin获取的RefreshToken，无论是调用ninja的刷新还是官方的刷新，都不会变

从/auth/token获取的RefreshToken，无论是调用ninja的刷新还是官方的刷新，都会变（ninja由于返回的RefreshToken不是新的，所以第二次刷新403）

**Comment by gngpp** [comment]
你刷的啥玩意啊，platform登录？

**Comment by lazzman** [comment]
1.调用`/auth/token`登录
![token](https://github.com/gngpp/ninja/assets/20707207/627f1933-6ac4-460e-9ceb-a5708d87489d)

2.调用官方刷新
![image](https://github.com/gngpp/ninja/assets/20707207/8a7163ac-31fe-4dbe-9935-8148122a3724)

**Comment by gngpp** [comment]
这两个就不是一个东西，两个平台的。不过也修复了，我直接返回官方的response 不做修改

**Comment by lazzman** [comment]
> 这两个就不是一个东西，两个平台的。不过也修复了，我直接返回官方的response 不做修改

新人不太懂请多包涵~
我想说明的问题是：
调用`/auth/token`获取到的refreshToken（option:platfrom），再调用`/auth/refresh_token`时，ninja返回的refreshToken还是以前的refreshToken，但实际上这个refreshToken已经失效了，所以再次调用`/auth/refresh_token`时，就会提示403

**Comment by gngpp** [comment]
不过你刷这玩意有啥用，也能用chatgpt聊天？

**Comment by lazzman** [comment]
1.调用/auth/token获取refreshTokenA
![image](https://github.com/gngpp/ninja/assets/20707207/57d5bd86-3236-4a04-843c-903ef5c917e3)

2.调用/auth/refresh_token刷新refreshTokenA，ninja此时返回的还是refreshTokenA
![image](https://github.com/gngpp/ninja/assets/20707207/5ad27d0c-b7fc-4e3d-a6e3-aa2fefe7e3a6)

3.再次调用/auth/refresh_token刷新refreshTokenA，ninja此时返回403
![image](https://github.com/gngpp/ninja/assets/20707207/6816f597-a164-4343-9fb2-e57c456fae84)

**Comment by lazzman** [comment]
> 不过你刷这玩意有啥用，也能用chatgpt聊天？

我是通过 https://github.com/Yanyutin753/refresh-gpt-chat.git 这个项目发现的这个问题，这个项目使用refresh_token作为请求头的，发现第二次调用refreshToken接口总是报错

**Comment by zzhhxx** [comment]
> > 不过你刷这玩意有啥用，也能用chatgpt聊天？
> 
> 我是通过 https://github.com/Yanyutin753/refresh-gpt-chat.git 这个项目发现的这个问题，这个项目使用refresh_token作为请求头的，发现第二次调用refreshToken接口总是报错

因为这个项目里面的refreshtoken不是platform里面的，而是PN之前遗留的，请仔细看readme
`完美继承pandoraNext留下的refresh_token`
