### ISSUE TITLE
项目不支持AARCH64处理器运行吗？会报exec format error

### ISSUE THREAD

**Issue by GloriaJohne** [gngpp/ninja#521]
项目不支持AARCH64处理器运行吗？会报exec format error

**Comment by gngpp** [comment]
你下错架构了吧

**Comment by GloriaJohne** [comment]
使用[ninja-0.9.25-aarch64-unknown-linux-musl.tar.gz](https://github.com/gngpp/ninja/releases/download/v0.9.25/ninja-0.9.25-aarch64-unknown-linux-musl.tar.gz)运行时   会报错“Segmentation fault”的     
系统是aarch64的centos 7.9

**Comment by gngpp** [comment]
运行`uname -a`

**Comment by gngpp** [comment]
**no problem**
<img width="871" alt="image" src="https://github.com/gngpp/ninja/assets/51810656/be042b62-d6d4-413b-a03e-a177783995cf">

**Comment by gngpp** [comment]
你换个设备吧
