### ISSUE TITLE
# Not Working New Version `v0.9.25` Chat2API Is working but the webpage is not showing

### ISSUE THREAD

**Issue by Niansuh** [gngpp/ninja#522]
# Not Working New Version `v0.9.25` Chat2API Is working but the webpage is not showing

![image](https://github.com/gngpp/ninja/assets/139365289/2c49aa19-ad9c-494d-b894-3e73b010f2cf)

![image](https://github.com/gngpp/ninja/assets/139365289/c6d691c1-ab1e-4833-8278-a4e2b8ffd3b4)

Please Solve

**Comment by gngpp** [comment]
Please check clearly what updates have been made in the document before asking questions.

**Comment by mouxangithub** [comment]
> 在提出问题之前，请仔细检查文档中进行了哪些更新。

似乎我配置了也无法起来，我的docker-copose为
```shell
  ninja:
    container_name: ninja
    image: gngpp/ninja:latest
    restart: always
    environment:
      - BIND=172.18.0.4:7999
      - ENABLE_WEBUI=true
      - ENABLE_ARKOSE_PROXY=true
      - ENABLE_FILE_PROXY=true
      - ARKOSE_SOLVER=Fcsrv
      - ARKOSE_ENDPOINT=http://172.18.0.7:8000/task
      - ARKOSE_GPT3_EXPERIMENT=true
      - ARKOSE_GPT3_EXPERIMENT_SOLVER=true
    command: run
    ports:
      - 7999
    networks:
      openai:
        ipv4_address: 172.18.0.4
```

一直给我报错
```shell
error: the following required arguments were not provided:
--arkose-endpoint <ARKOSE_ENDPOINT>
```

**Comment by Niansuh** [comment]
https://github.com/gngpp/ninja/assets/139365289/ba9471a8-1d8d-41f4-8b19-e6be9418b990

Check the video

this is my dockerfile

```Dockerfile
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y curl

RUN version=$(basename $(curl -sL -o /dev/null -w %{url_effective} https://github.com/gngpp/ninja/releases/latest)) \
    && base_url="https://github.com/gngpp/ninja/releases/expanded_assets/$version" \
    && latest_url=https://github.com/$(curl -sL $base_url | grep -oP 'href=".*x86_64.*musl\.tar\.gz(?=")' | sed 's/href="//') \
    && curl -Lo ninja.tar.gz $latest_url \
    && tar -xzf ninja.tar.gz


ENV LANG=en_US.UTF-8 DEBIAN_FRONTEND=noninteractive LANGUAGE=en_US.UTF-8 LC_ALL=C

RUN cp ninja /bin/ninja
RUN mkdir /.ninja && chmod 777 /.ninja

CMD ["/bin/ninja","run"]

**Comment by Niansuh** [comment]
old version is working perfectly

**Comment by Niansuh** [comment]
sit this is showing in container logs in hugging face spaces this please help

2024-02-05T06:10:26.385932Z INFO openai::serve: Enable WebUI: false

**Comment by jetaimy** [comment]
大佬的文档更新了：“--enable-webui, 默认关闭自带的WebUI，使用此参数开启，必须设置--arkose-endpoint，如果你的出口访问域名是example.com，那么你需要设置--arkose-endpoint https://example.com”
docker run -d -p 7999:7999  --net=host \
  -e HOSTNAME=127.0.0.1 \
  -e LOG=info \
  -v ~/.ninja:/root/.ninja \
  gngpp/ninja:latest run --enable-webui --arkose-endpoint https://example.com/
