### ISSUE TITLE
How to enable web ui

### ISSUE THREAD

**Issue by Niansuh** [gngpp/ninja#524]
How to enable web ui

please guide sir

**Comment by Niansuh** [comment]
Working Sir

**Comment by jetaimy** [comment]
大佬的文档更新了：“--enable-webui, 默认关闭自带的WebUI，使用此参数开启，必须设置--arkose-endpoint，如果你的出口访问域名是example.com，那么你需要设置--arkose-endpoint https://example.com”
docker run -d -p 7999:7999  --net=host \
  -e HOSTNAME=127.0.0.1 \
  -e LOG=info \
  -v ~/.ninja:/root/.ninja \
  gngpp/ninja:latest run --enable-webui --arkose-endpoint https://example.com/

**Comment by PaienNate** [comment]
> 大佬的文档更新了：“--enable-webui, 默认关闭自带的WebUI，使用此参数开启，必须设置--arkose-endpoint，如果你的出口访问域名是example.com，那么你需要设置--arkose-endpoint [https://example.com”](https://example.com%E2%80%9D) docker run -d -p 7999:7999 --net=host -e HOSTNAME=127.0.0.1 -e LOG=info -v ~/.ninja:/root/.ninja gngpp/ninja:latest run --enable-webui --arkose-endpoint https://example.com/

可否问一下所谓出口访问域名是指什么？比如我服务器的地址为A，挂的梯子的地址为B，是选择B的地址，还是另外有其他的地址设定？

**Comment by gngpp** [comment]
你从https://fuck.openai.com访问网站，那么arkose endpoint 就要设置https://fuck.openai.com

**Comment by PaienNate** [comment]
> 你从`https://fuck.openai.com`访问网站，那么`arkose endpoint`就要设置`https://fuck.openai.com`。字面意思不要想太复杂了，这个地址是给你客户端能访问的到才有用。如果你设置`http://localhost:7999`，只能内网访问arkose接口，外网就没用了

原来如此，感谢大佬讲解。
