### ISSUE TITLE
thread 'main' panicked at crates/openai/src/context/arkose/mod.rs:51:14: Failed to create arkose database: RedbDatabaseError(DatabaseAlreadyOpen) note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace Aborted 

### ISSUE THREAD

**Issue by UtopiaLee** [gngpp/ninja#525]
thread 'main' panicked at crates/openai/src/context/arkose/mod.rs:51:14:
Failed to create arkose database: RedbDatabaseError(DatabaseAlreadyOpen)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted 

Arm 架构

**Comment by fanwenlin** [comment]
遇到了相同的问题。可以分享下是怎么解决的吗？
