### ISSUE TITLE
升级最新版本9.26后，登录页Continue按钮无效了。

### ISSUE THREAD

**Issue by yuanpeigen007** [gngpp/ninja#534]
升级最新版本9.26后，登录页Continue按钮无效了。

**Comment by gngpp** [comment]
按F12截图重新进入一次登录流程请求记录

**Comment by gngpp** [comment]
如果你用了乱七八糟的反向代理，那么这个问题可以关闭了

**Comment by gngpp** [comment]
经其他人测试都没有你这个问题。

**Comment by yuanpeigen007** [comment]
enable_webui = true
ARKOSE ENDPOINT = https://XXX.shop
enable_file_proxy = true  配置可以吗

**Comment by chatbom** [comment]
问题怎么解决了？
