### ISSUE TITLE
请问 GPT 3.5 会话不会产生 HAR 日志文件吗

### ISSUE THREAD

**Issue by nD9r2Dhr** [gngpp/ninja#535]
请问佬，GPT 3.5 会话不会产生 HAR 日志文件吗？
目前我的情况是，web-ui 一切正常，可以使用账密登录，也可以请求到 accesstoken 等；但是登录接口 `/auth/token` 返回 `{"code":400,"msg":"Invalid arkose token (No solver available or solver is invalid)"}`，无法登录以及进一步操作。一定要上传 HAR 文件吗，我怎么也找不到那条请求 (`https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147`)..还是说一定要 GPT 4?
请佬解惑！谢谢！

![](https://i.imgur.com/j6r61cC.gif)

**Comment by gngpp** [comment]
抓登录的HAR，你抓GPT4干什么

**Comment by nD9r2Dhr** [comment]
> 抓登录的，你抓GPT4干什么

谢佬，搞定了，刚接触没搞明白。就祝你龙年大吉吧😄

以下给其它懵逼的小白作参考。
![](https://i.imgur.com/K4UlNu3.png)
![](https://i.imgur.com/zrVQhAA.png)
