### ISSUE TITLE
ChatGPT error 418: {"detail":{"message":"Client challenge required","code":"challenge_required"}}

### ISSUE THREAD

**Issue by Niansuh** [gngpp/ninja#536]
ChatGPT error 418: {"detail":{"message":"Client challenge required","code":"challenge_required"}}

![image](https://github.com/gngpp/ninja/assets/139365289/d940ab32-8d8c-45cf-8170-4ba11a535dea)

**Comment by Niansuh** [comment]
how to solve

**Comment by gngpp** [comment]
There is no way you can do it without using

**Comment by Niansuh** [comment]
working
