### ISSUE TITLE
ninja 出现 Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by heurainbow** [gngpp/ninja#539]
如题。
官方网页直接访问没有问题。这是什么原因？IP问题么

**Comment by spammenotinoz** [comment]
Suspect IP, I had this issue, then used WARP for a few days, then went back to direct and was fine.

**Comment by gitxws** [comment]
me too，直连官网，ip都没有问题，就是ninja报错"Our systems have detected unusual activity from your system. Please try again later."

**Comment by rambolee** [comment]
尝试更新到了最新的ninja的docker版本，目前依旧出现。

**Comment by gngpp** [comment]
别用了 年后就跑路了。没空维护了

**Comment by wwlmm** [comment]
> 别用了 年后就跑路了。没空维护了

希望项目一直活着 新年快乐 请大佬喝咖啡
