### ISSUE TITLE
api模式还是不行

### ISSUE THREAD

**Issue by chenjingwei0103** [gngpp/ninja#542]
我换了最新版本[0.9.28]版本，然后配置-arkose-endpoint使用其他平台地址，页面上是正常使用了，但是使用api的时候data: {"message": null, "conversation_id": "fd387345-6181-44d7-b4a6-1c1117d507fc", "error": "Our systems have detected unusual activity from your system. Please try again later."}提示这个，是哪里出问题了，能不能帮忙讲解下

**Comment by gngpp** [comment]
项目不打算维护了，不要使用了

**Comment by wwlmm** [comment]
真可惜
