### ISSUE TITLE
登录需要拼图了

### ISSUE THREAD

**Issue by nankaine** [gngpp/ninja#547]
平时登陆的号，突然需要拼图了。 
![ai2](https://github.com/gngpp/ninja/assets/94109329/89b26c66-69c6-4db7-8dc9-b223d743c9a7)

[
![ai1](https://github.com/gngpp/ninja/assets/94109329/8c0b80b9-7317-4a0c-9ff1-f7fe4d3d5361)
](url)
使用的配置如下：
```
level = "info"
bind = "127.0.0.1:5019"
concurrent_limit = 65535
timeout = 600
connect_timeout = 60
tcp_keepalive = 60
no_keepalive = false
pool_idle_timeout = 90
enable_direct = true
cookie_store = true
fastest_dns = false
enable_webui = false
enable_file_proxy = false
enable_arkose_proxy = false
arkose_gpt3_experiment = false
arkose_gpt3_experiment_solver = false
arkose_solver = "fcsrv"
arkose_solver_limit = 3
tb_enable = false
tb_strategy = "mem"
tb_capacity = 60
tb_fill_rate = 1
tb_expired = 86400
impersonate_uas = ["edge99","edge101"]
visitor_email_whitelist = ["d@freels.link"]
```

目前已经上传了auth的har文件。 依旧有这个情况。
这个是否需要引入打码程序呢

目前使用api来获取token，报错
```
{
    "code": 400,
    "msg": "Accidentally jumped back to the login homepage, please try again."
}
```

请教一下，这个需要怎么处理呢
参考了https://github.com/gngpp/ninja/issues/514
是需要引入tguess来处理吗

**Comment by gngpp** [comment]
网页不一样的，不走任何什么har，不用tguess，如果官网也登录不了那么无解

**Comment by gngpp** [comment]
拼图不奇怪的，特征黑。打了能登录就没事了

**Comment by Niansuh** [comment]
hi @gngpp i am using chat2api but yesterday my 2 chatgpt account bans

**Comment by Niansuh** [comment]
working bro in chatgpt-web using /backend-api/conversation

**Comment by gngpp** [comment]
黑了正常，以后gpt3.5都没有得用了。因为上cf验证码了，arkose难度是最低的，cf是最难的

**Comment by Niansuh** [comment]
in future no way to use gpt3.5 as a API

**Comment by Niansuh** [comment]
in my other chatgpt account the chat2api using access token is not working

**Comment by Niansuh** [comment]
yes

**Comment by gngpp** [comment]
有些号是wss，第三方客户端是没有适配的，我已经在适配代理了，这几天内完工

**Comment by Niansuh** [comment]
wait @gngpp how to use backendapi in one conversation

**Comment by yuanshangyujingshierlou** [comment]
> 有些号是wss，第三方客户端是没有适配的，我已经在适配代理了，这几天内完工

狠狠的支持的大佬，已赞助，兄弟们也给大佬点支持呀，买杯咖啡也好的
