### ISSUE TITLE
为什么成功在vps部署后，在网页打开会显示找不到此 *** 页面 HTTP ERROR 404

### ISSUE THREAD

**Issue by vc9988** [gngpp/ninja#549]
如标题所示，请求帮助

**Comment by gngpp** [comment]
看wiki启动参数描述，不详细看，默认UI是关闭的

**Comment by vc9988** [comment]
谢谢您的回答，因为我是小白，没有能找到说明，我在vps里用的是
docker run --rm -it -d -p 7999:7999 --name=ninja \
  -e LOG=info \
  ghcr.io/gngpp/ninja:latest run
能否给我正确的docker命令？

**Comment by gebederry** [comment]
https://github.com/gngpp/ninja/wiki/3-Http-%E6%9C%8D%E5%8A%A1#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
`--enable-webui`，默认关闭自带的WebUI，使用此参数开启，必须设置`--arkose-endpoint`，设置为你的域名/主机，例如: http://127.0.0.1:7999/

**Comment by vc9988** [comment]
谢谢您的帮助，我在成功的写了配置文件，在前端模式能正常运行，在后端模式不能，发现应该是目录问题，我在后端用sudo ninja restart -C serve.toml成功运行，但用accessToken登录显示Invalid session-token,为什么，请指点


________________________________

**Comment by gngpp** [comment]
不再支持access token登录

**Comment by vc9988** [comment]
那用什么token登录呢?
________________________________

**Comment by gngpp** [comment]
直接账号登陆不好吗？用session token或者账号

**Comment by vc9988** [comment]
用用session token登录提示"code": 500,
    "msg": "error sending request for url (https://chat.openai.com/): error trying to connect: tcp bind local error: Address not available (os error 99)"

________________________________
